function auth_(token){assert_(typeof token==='string'&&/^[a-f0-9-]{36}$/i.test(token),'AUTH_EXPIRED','Silakan login kembali.');var hash=digest_(token),cache=CacheService.getScriptCache(),cached=cache.get('session:'+hash),session=cached?JSON.parse(cached):null;
  // Revocation/expiry is always checked in Sheets; cached user roles are never authoritative.
  session=readTable_('Sessions',false).find(function(r){return r.token_hash===hash;});assert_(session&&!session.revoked&&Date.parse(session.expires_at)>Date.now(),'AUTH_EXPIRED','Sesi berakhir. Login kembali untuk melanjutkan sinkronisasi.');
  var user=readTable_('Users',false).find(function(r){return r.id===session.user_id;});assert_(user&&user.active,'FORBIDDEN','Akun tidak aktif.');cache.put('session:'+hash,JSON.stringify(session),Math.min(21600,Math.floor((Date.parse(session.expires_at)-Date.now())/1000)));return user;
}
function role_(user,roles){assert_(roles.indexOf(user.role)!==-1,'FORBIDDEN','Peran Anda tidak memiliki akses tindakan ini.');}
function pinHash_(pin,salt){var pepper=PropertiesService.getScriptProperties().getProperty('AUTH_PEPPER');assert_(pepper,'SETUP_REQUIRED','AUTH_PEPPER belum dibuat. Jalankan setup().');return digest_(salt+'|'+pin+'|'+pepper);}
function validatePin_(pin){assert_(typeof pin==='string'&&/^\d{8,12}$/.test(pin),'VALIDATION','PIN harus 8–12 digit.');return pin;}
function limit_(ctx,key,max,seconds){var hash=digest_(key),row=ctx.table('RateLimits').find(function(r){return r.key===hash;}),now=Date.now();if(!row||now-Date.parse(row.window_start)>=seconds*1000){row=row||ctx.add('RateLimits',{key:hash,count:0,window_start:now_()},hash);row.count=0;row.window_start=now_();}if(row.count>=max)return false;row.count++;ctx.put('RateLimits',row);return true;}
function login_(ctx,p){var username=str_(p.username,60,true).toLowerCase(),pin=str_(p.pin,12,true),allowed=limit_(ctx,'login:'+username,8,900);
  if(!allowed)return {_error:{code:'RATE_LIMIT',message:'Terlalu banyak percobaan. Tunggu 15 menit.'}};
  var u=ctx.table('Users').find(function(r){return r.username===username;}),dummy=pinHash_(pin,u?u.pin_salt:'nonexistent');
  if(!u||!u.active||!equal_(dummy,u.pin_hash))return {_error:{code:'LOGIN_FAILED',message:'Username atau PIN salah.'}};
  var token=uuid_(),expiry=new Date(Date.now()+12*3600000).toISOString();ctx.add('Sessions',{token_hash:digest_(token),user_id:u.id,expires_at:expiry,revoked:false},digest_(token));audit_(ctx,'login','Users',u.id,{});return {token:token,expiresAt:expiry,user:cleanPublicUser_(u)};
}
function logout_(ctx,p,token){var r=ctx.table('Sessions').find(function(s){return s.token_hash===digest_(token);});if(r){r.revoked=true;ctx.put('Sessions',r);CacheService.getScriptCache().remove('session:'+r.token_hash);}return {loggedOut:true};}
function saveUser_(ctx,p){var username=str_(p.username,60,true).toLowerCase();assert_(/^[a-z0-9_.-]{3,60}$/.test(username),'VALIDATION','Username tidak valid.');var duplicate=ctx.table('Users').find(function(u){return u.username===username&&u.id!==p.id;});assert_(!duplicate,'DUPLICATE','Username sudah dipakai.');var role=one_(p.role,['spg','fm','supervisor','client_viewer','admin']),active=bool_(p.active),r=p.id?entity_(ctx,'Users',id_(p.id)):ctx.add('Users',{},username);
  if(r.id===ctx.actor.id){assert_(active&&role==='admin','VALIDATION','Admin tidak boleh menonaktifkan atau menurunkan peran sendiri.');}
  if(p.pin){r.pin_salt=uuid_();r.pin_hash=pinHash_(validatePin_(p.pin),r.pin_salt);}assert_(r.pin_hash,'VALIDATION','PIN wajib untuk pengguna baru.');r.username=username;r.name=str_(p.name,100,true);r.role=role;r.active=active;r.area=str_(p.area,100);r.workshop_ids=listIds_(p.workshop_ids||[]);ctx.put('Users',r);audit_(ctx,'user.save','Users',r.id,{role:role,active:active});return cleanPublicUser_(r);
}
function readiness_(ctx,userId){var courses=ctx.table('Training').filter(function(t){return t.active&&t.approved;}),results=ctx.table('QuizResults');return courses.length>0&&courses.every(function(t){return results.some(function(r){return r.user_id===userId&&r.training_id===t.id&&r.training_version===t.version&&r.pass&&r.practical_pass;});});}
function submitTraining_(ctx,p){var t=entity_(ctx,'Training',id_(p.training_id));assert_(t.active&&t.approved,'VALIDATION','Materi belum disetujui.');assert_(Array.isArray(p.answers)&&p.answers.length===t.questions.length,'VALIDATION','Jawab semua pertanyaan.');var right=0;t.questions.forEach(function(q,i){var ans=num_(p.answers[i],0,q.options.length-1);if(ans===q.correct)right++;});var score=Math.round(100*right/t.questions.length),r=ctx.add('QuizResults',{user_id:ctx.actor.id,training_id:t.id,training_version:t.version,score:score,answers:p.answers,pass:score>=Math.max(80,t.pass_score),practical_pass:false},t.id);return {id:r.id,score:score,pass:r.pass,practicalPass:false};}
function practical_(ctx,p){var r=entity_(ctx,'QuizResults',id_(p.result_id));assert_(r.pass,'VALIDATION','Quiz belum lulus.');r.practical_pass=bool_(p.pass);r.practical_by=ctx.actor.id;r.practical_at=now_();ctx.put('QuizResults',r);audit_(ctx,'training.practical','QuizResults',r.id,{pass:r.practical_pass});return {id:r.id,practical_pass:r.practical_pass};}
