function createLead_(ctx,p){var outlet=entity_(ctx,'Outlets',id_(p.outlet_id));assert_(outletAccess_(ctx,outlet.id),'FORBIDDEN','Outlet bukan penugasan Anda.');var permission=bool_(p.contact_permission),lead=ctx.add('Leads',{user_id:ctx.actor.id,outlet_id:outlet.id,category:str_(p.category,100,true),need:str_(p.need,1000,true),contact_permission:permission,owner_id:'',recipient_id:'',status:'recorded',next_action:str_(p.next_action,500),outcome:'',sale_value:0},'lead');
  if(permission){var contact=p.contact||{};ctx.add('LeadContacts',{lead_id:lead.id,name:str_(contact.name,100,true),phone:phone_(contact.phone)},lead.id);}ctx.add('LeadEvents',{lead_id:lead.id,event:'recorded',actor_id:ctx.actor.id,note:'Permission: '+permission},lead.id);audit_(ctx,'lead.create','Leads',lead.id,{permission:permission});return {id:lead.id,status:lead.status};}
function updateLead_(ctx,p){var l=entity_(ctx,'Leads',id_(p.lead_id)),event=one_(p.event,['validate','handoff','acknowledge','respond','outcome']),client=ctx.actor.role==='client_viewer',note=str_(p.note,1000,true);
  if(client){assert_(['acknowledge','respond','outcome'].indexOf(event)!==-1&&l.recipient_id===ctx.actor.id,'FORBIDDEN','Hanya penerima client yang ditunjuk dapat merespons.');}
  if(event==='validate'){role_(ctx.actor,MANAGERS_);assert_(l.status==='recorded','CONFLICT','Lead sudah divalidasi.');assert_(l.need&&l.category&&l.contact_permission,'VALIDATION','Opportunity harus ada kebutuhan relevan + izin kontak.');var recipient=entity_(ctx,'Users',id_(p.recipient_id));assert_(recipient.active&&recipient.role==='client_viewer','VALIDATION','Pilih penerima client aktif bernama.');var owner=entity_(ctx,'Users',id_(p.owner_id));assert_(owner.active&&MANAGERS_.indexOf(owner.role)!==-1,'VALIDATION','PIC harus supervisor/admin.');l.owner_id=owner.id;l.recipient_id=recipient.id;l.status='validated';l.validated_at=now_();l.sla_due_at=workingDue_(l.validated_at,config_(ctx).sla_working_days,config_(ctx));}
  if(event==='handoff'){role_(ctx.actor,MANAGERS_);assert_(l.status==='validated','CONFLICT','Validasi lead terlebih dahulu.');l.status='handed_off';}
  if(event==='acknowledge'){assert_(l.status==='handed_off','CONFLICT','Lead belum diserahkan.');assert_(l.recipient_id===ctx.actor.id,'FORBIDDEN','Hanya penerima bernama dapat acknowledge.');l.ack_at=now_();l.status='acknowledged';}
  if(event==='respond'){assert_(l.status==='acknowledged'||l.status==='responded','CONFLICT','Acknowledge terlebih dahulu.');assert_(l.recipient_id===ctx.actor.id,'FORBIDDEN','Respons harus dari penerima client.');assert_(typeof p.stock_response==='string'&&typeof p.price_response==='string','VALIDATION','Konfirmasi stok dan harga diperlukan.');note+=' | Stock: '+str_(p.stock_response,300,true)+' | Price: '+str_(p.price_response,300,true);l.status='responded';}
  if(event==='outcome'){assert_(ctx.actor.role==='client_viewer'&&l.recipient_id===ctx.actor.id,'FORBIDDEN','Sales outcome hanya dikonfirmasi penerima client.');assert_(l.status==='responded','CONFLICT','Konfirmasi respons stok/harga dahulu.');l.outcome=one_(p.outcome,['sale','no_sale','pending']);if(l.outcome==='sale'){l.transaction_ref=str_(p.transaction_ref,150,true);l.sale_value=num_(p.sale_value,0,100000000000);l.verified_at=now_();l.verified_by=ctx.actor.id;}if(l.outcome!=='pending')l.status='closed';}
  l.next_action=str_(p.next_action,500,true);ctx.put('Leads',l);ctx.add('LeadEvents',{lead_id:l.id,event:event,note:note,actor_id:ctx.actor.id},l.id+':'+event);audit_(ctx,'lead.'+event,'Leads',l.id,{status:l.status});return {id:l.id,status:l.status};}
function listLeads_(ctx){var u=ctx.actor,manager=MANAGERS_.indexOf(u.role)!==-1,client=u.role==='client_viewer';return ctx.table('Leads').filter(function(l){return manager||(client?l.recipient_id===u.id:l.user_id===u.id);}).map(function(l){var out=entity_(ctx,'Outlets',l.outlet_id),qualified=!!(l.need&&l.category&&l.contact_permission&&l.recipient_id),overdue=l.sla_due_at&&Date.parse(l.sla_due_at)<Date.now()&&l.status==='validated';return Object.assign({},l,{outlet_name:out.name,qualified:qualified,overdue:!!overdue,age_days:l.validated_at?Math.max(0,dayDiff_(today_(),day_(l.validated_at))):0});});}
function leadContacts_(ctx,p){var id=id_(p.lead_id);entity_(ctx,'Leads',id);return ctx.table('LeadContacts').filter(function(c){return c.lead_id===id;});}
