function customerAllowed_(ctx,c){return MANAGERS_.indexOf(ctx.actor.role)!==-1||c.created_by===ctx.actor.id&&outletAccess_(ctx,c.workshop_id);}
function pointsBalance_(ctx,id){var today=today_();return Math.max(0,ctx.table('PointsLedger').filter(function(r){return r.customer_id===id&&(!r.expires_at||r.expires_at.slice(0,10)>=today);}).reduce(function(n,r){return n+r.points;},0));}
function tier_(points,conf){return points>=conf.tier_platinum?'Platinum':points>=conf.tier_gold?'Gold':'Silver';}
function consent_(ctx,c,optin,source,evidence){var conf=config_(ctx);c.wa_opt_in=optin;c.consent_at=now_();c.consent_source=source;ctx.add('Consents',{customer_id:c.id,opt_in:optin,timestamp:now_(),source:source,actor_id:ctx.actor.id,text_version:conf.consent_text_version,evidence:str_(evidence,1000,true),number_hash:digest_(c.phone)},c.id+':'+Object.keys(ctx.changes.Consents||{}).length);audit_(ctx,optin?'consent.optin':'consent.optout','Customers',c.id,{source:source,text_version:conf.consent_text_version});}
function nextService_(ctx,last,kind,odometer){var conf=config_(ctx),calendar=addMonths_(last,conf.service_intervals[kind]||6),km=conf.service_odometer_intervals[kind]||conf.odometer_interval_km,projected=conf.projected_km_per_day>0?addDays_(last,Math.ceil(km/conf.projected_km_per_day)):calendar;return {date:projected<calendar?projected:calendar,odometer:odometer!==''&&odometer!==undefined?Number(odometer)+km:''};}
function upsertCustomer_(ctx,p){var ph=phone_(p.phone),plate=plate_(p.plate),workshop=id_(p.workshop_id);assert_(outletAccess_(ctx,workshop),'FORBIDDEN','Bengkel tidak sesuai penugasan.');assert_(ctx.table('Workshops').some(function(w){return w.active&&w.outlet_id===workshop;}),'VALIDATION','Pilih workshop aktif.');var rows=ctx.table('Customers'),c=p.id?entity_(ctx,'Customers',id_(p.id)):rows.find(function(r){return !r.deleted&&r.phone===ph&&r.plate===plate;});if(c)assert_(customerAllowed_(ctx,c),'FORBIDDEN','Pelanggan sudah terdaftar; hubungi supervisor untuk pembaruan.');if(!c)c=ctx.add('Customers',{cycle_id:uuid_(),reminder_attempts:0,deleted:false},ph+plate);assert_(!rows.some(function(r){return !r.deleted&&r.id!==c.id&&r.phone===ph&&r.plate===plate;}),'DUPLICATE','Nomor + plat telah terdaftar.');
  var optin=bool_(p.wa_opt_in),source=one_(p.consent_source,['spg','fm','workshop']),last=date_(p.last_service_date),kind=one_(p.service_type,['general','brake_check','shock_absorber']);assert_(last<=today_(),'VALIDATION','Tanggal servis terakhir tidak boleh di masa depan.');if(optin)assert_(p.consent_confirmed===true,'CONSENT_REQUIRED','Centang persetujuan WhatsApp dari pelanggan.');var changed=c.wa_opt_in!==optin||c.phone!==ph||!c.consent_at;
  Object.assign(c,{name:str_(p.name,100,true),phone:ph,plate:plate,brand:str_(p.brand,100,true),model:str_(p.model,100,true),year:num_(p.year,1950,Number(today_().slice(0,4))+1),birthday:p.birthday?date_(p.birthday):'',workshop_id:workshop,last_service_date:last,odometer:p.odometer===''||p.odometer===undefined?'':num_(p.odometer,0,3000000),service_type:kind,next_service_date:addMonths_(last,config_(ctx).service_intervals[kind]||6)});
  var due=nextService_(ctx,last,kind,c.odometer);c.next_service_date=due.date;c.next_service_odometer=due.odometer;if(changed)consent_(ctx,c,optin,source,p.consent_evidence||'Checkbox confirmed in field app: '+config_(ctx).consent_text);ctx.put('Customers',c);audit_(ctx,'customer.upsert','Customers',c.id,{workshop:workshop});return {id:c.id,label:'Pelanggan •••'+ph.slice(-4),wa_opt_in:c.wa_opt_in,next_service_date:c.next_service_date};
}
function listCustomers_(ctx){var manager=MANAGERS_.indexOf(ctx.actor.role)!==-1,conf=config_(ctx);return ctx.table('Customers').filter(function(c){return !c.deleted&&(manager||customerAllowed_(ctx,c));}).map(function(c){var points=pointsBalance_(ctx,c.id),extra={points:points,tier:tier_(points,conf),label:'Pelanggan •••'+c.phone.slice(-4)};return manager?Object.assign({},c,extra):Object.assign({id:c.id,workshop_id:c.workshop_id,wa_opt_in:c.wa_opt_in,next_service_date:c.next_service_date},extra);});}
function optoutCustomer_(ctx,p){var c=entity_(ctx,'Customers',id_(p.customer_id));consent_(ctx,c,false,'workshop',str_(p.reason,500)||'Admin opt-out');ctx.put('Customers',c);cancelPendingMessages_(ctx,c.id);return {id:c.id,wa_opt_in:false};}
function cancelPendingMessages_(ctx,id){ctx.table('MessageLog').filter(function(m){return m.customer_id===id&&['queued','retry','manual_pending'].indexOf(m.status)!==-1;}).forEach(function(m){m.status='cancelled';m.error='Customer opted out';m.manual_url='';ctx.put('MessageLog',m);});}
function creditPoints_(ctx,customer,reason,ref,amount){if(ctx.table('PointsLedger').some(function(r){return r.customer_id===customer&&r.ref===ref&&r.reason===reason;}))return;ctx.add('PointsLedger',{customer_id:customer,points:amount,reason:reason,ref:ref,expires_at:addDays_(today_(),config_(ctx).points_expiry_days)},reason+':'+ref);}
function serviceCustomer_(ctx,p){var c=entity_(ctx,'Customers',id_(p.customer_id)),kind=one_(p.kind,['visit','purchase']),date=date_(p.date);assert_(!c.deleted&&date<=today_(),'VALIDATION','Tanggal layanan tidak valid.');if(kind==='purchase')assert_(ctx.actor.role==='client_viewer','FORBIDDEN','Pembelian TRW harus diverifikasi client/partner resmi.');else role_(ctx.actor,MANAGERS_);var transaction=str_(p.transaction_ref,150,true);assert_(!ctx.table('ServiceEvents').some(function(e){return e.kind===kind&&e.transaction_ref===transaction;}),'DUPLICATE','Transaksi layanan sudah dikonfirmasi.');
  var reminder=ctx.table('MessageLog').filter(function(m){return m.customer_id===c.id&&m.stage&&m.sent_at&&day_(m.sent_at)<=date&&['sent','delivered'].indexOf(m.status)!==-1&&m.cycle_id===c.cycle_id;}).sort(function(a,b){return b.sent_at.localeCompare(a.sent_at);})[0];var event=ctx.add('ServiceEvents',{customer_id:c.id,workshop_id:c.workshop_id,date:date,kind:kind,verified_by:ctx.actor.id,transaction_ref:transaction,sale_value:kind==='purchase'?num_(p.sale_value,0,100000000000):0,return_ref:str_(p.return_ref,150),reminder_id:kind==='visit'&&reminder?reminder.id:''},kind+':'+transaction);var conf=config_(ctx);creditPoints_(ctx,c.id,kind==='visit'?'workshop_visit':'verified_trw_purchase',event.id,kind==='visit'?conf.points_visit:conf.points_verified_purchase);
  if(kind==='visit'){c.last_service_date=date;c.next_service_date=addMonths_(date,conf.service_intervals[c.service_type]||6);c.odometer=p.odometer===undefined?c.odometer:num_(p.odometer,0,3000000);var due=nextService_(ctx,date,c.service_type,c.odometer);c.next_service_date=due.date;c.next_service_odometer=due.odometer;c.cycle_id=uuid_();c.reminder_attempts=0;ctx.put('Customers',c);ctx.table('MessageLog').filter(function(m){return m.customer_id===c.id&&m.stage&&['queued','retry','manual_pending'].indexOf(m.status)!==-1;}).forEach(function(m){m.status='cancelled';m.error='Service cycle reset';m.manual_url='';ctx.put('MessageLog',m);});}
  if(kind==='purchase'&&conf.voucher_after_purchase)issueVoucherFor_(ctx,c.id,conf.voucher_after_purchase,'purchase:'+event.id);audit_(ctx,'customer.service','ServiceEvents',event.id,{kind:kind});return {event_id:event.id,points:pointsBalance_(ctx,c.id),next_service_date:c.next_service_date};
}
function saveVoucherTemplate_(ctx,p){var t=p.id?entity_(ctx,'VoucherTemplates',id_(p.id)):ctx.add('VoucherTemplates',{},'template'),type=one_(p.type,['fixed','percent','free_check','free_item']);Object.assign(t,{name:str_(p.name,150,true),type:type,value:num_(p.value,0,type==='percent'?100:10000000),min_spend:num_(p.min_spend,0,10000000000),validity_days:num_(p.validity_days,1,365),eligible_workshops:listIds_(p.eligible_workshops||[]),quota:num_(p.quota,1,1000000),terms:str_(p.terms,2000,true),active:bool_(p.active),approval_required:bool_(p.approval_required),cost:num_(p.cost||0,0,10000000)});t.eligible_workshops.forEach(function(id){entity_(ctx,'Outlets',id);});ctx.put('VoucherTemplates',t);audit_(ctx,'voucher.template.save','VoucherTemplates',t.id,{});return t;}
function code_(){var chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',seed=digest_(uuid_()+uuid_()),out='';for(var i=0;i<8;i++)out+=chars[parseInt(seed.slice(i*2,i*2+2),16)%chars.length];return 'TRW-'+out.slice(0,4)+'-'+out.slice(4);}
function issueVoucherFor_(ctx,customerId,templateId,ref){var c=entity_(ctx,'Customers',id_(customerId)),t=entity_(ctx,'VoucherTemplates',id_(templateId));assert_(!c.deleted&&t.active,'VALIDATION','Pelanggan/template tidak aktif.');assert_(!t.eligible_workshops.length||t.eligible_workshops.indexOf(c.workshop_id)!==-1,'VALIDATION','Workshop pelanggan tidak eligible.');var count=ctx.table('Vouchers').filter(function(v){return v.template_id===t.id;}).length;assert_(count<t.quota,'QUOTA_EXCEEDED','Kuota voucher habis.');var code=code_();while(ctx.table('Vouchers').some(function(v){return v.code===code;}))code=code_();var conf=config_(ctx),v=ctx.add('Vouchers',{customer_id:c.id,template_id:t.id,code:code,value:t.value,type:t.type,min_spend:t.min_spend,terms:t.terms,eligible_workshops:t.eligible_workshops,expires_at:addDays_(today_(),t.validity_days)+'T23:59:59+07:00',status:'issued',approval_status:t.approval_required||conf.loyalty_require_approval?'pending':'approved',approved_by:'',message_id:''},ref);audit_(ctx,'voucher.issue','Vouchers',v.id,{template_id:t.id});return v;}
function issueVoucher_(ctx,p){assert_(limit_(ctx,'voucher.issue:'+ctx.actor.id,30,3600),'RATE_LIMIT','Batas penerbitan 30 per jam.');var c=entity_(ctx,'Customers',id_(p.customer_id));assert_(customerAllowed_(ctx,c),'FORBIDDEN','Pelanggan tidak dapat diakses.');return issueVoucherFor_(ctx,c.id,id_(p.template_id),'manual');}
function approveVoucher_(ctx,p){var v=entity_(ctx,'Vouchers',id_(p.voucher_id));assert_(v.approval_status==='pending'&&v.status==='issued','CONFLICT','Voucher tidak menunggu persetujuan.');v.approval_status=bool_(p.approve)?'approved':'rejected';v.approved_by=ctx.actor.id;if(v.approval_status==='rejected'){v.status='void';v.void_reason=str_(p.reason,500,true);}ctx.put('Vouchers',v);audit_(ctx,'voucher.approve','Vouchers',v.id,{approval:v.approval_status});return {id:v.id,approval_status:v.approval_status};}
function listVouchers_(ctx){var manager=MANAGERS_.indexOf(ctx.actor.role)!==-1,client=ctx.actor.role==='client_viewer';return ctx.table('Vouchers').filter(function(v){if(manager||client)return true;var c=ctx.table('Customers').find(function(c){return c.id===v.customer_id;});return c&&customerAllowed_(ctx,c);}).map(function(v){var status=v.status;if(['issued','sent','delivered'].indexOf(status)!==-1&&Date.parse(v.expires_at)<Date.now())status='expired';if(client)return {id:v.id,template_id:v.template_id,type:v.type,value:v.value,status:status,approval_status:v.approval_status,expires_at:v.expires_at};return Object.assign({},v,{status:status});});}
function validateCode_(ctx,p){var code=str_(p.code,18,true).toUpperCase();assert_(/^TRW-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}$/.test(code),'VALIDATION','Format kode voucher tidak valid.');var v=ctx.table('Vouchers').find(function(v){return v.code===code;});assert_(v,'NOT_FOUND','Voucher tidak ditemukan.');assert_(v.status!=='redeemed','ALREADY_REDEEMED','Voucher sudah digunakan.');assert_(v.status!=='void'&&v.status!=='expired'&&Date.parse(v.expires_at)>=Date.now(),'EXPIRED','Voucher tidak aktif/kedaluwarsa.');assert_(v.approval_status==='approved','APPROVAL_REQUIRED','Voucher belum disetujui client.');var workshop=id_(p.workshop_id);assert_(outletAccess_(ctx,workshop),'FORBIDDEN','Workshop tidak dapat diakses.');assert_(ctx.table('Workshops').some(function(w){return w.active&&w.outlet_id===workshop;}),'VALIDATION','Bengkel tidak aktif.');assert_(!v.eligible_workshops.length||v.eligible_workshops.indexOf(workshop)!==-1,'NOT_ELIGIBLE','Voucher tidak berlaku di bengkel ini.');return v;}
function validateVoucher_(ctx,p){var v=validateCode_(ctx,p);return {id:v.id,code:v.code,type:v.type,value:v.value,min_spend:v.min_spend,terms:v.terms,expires_at:v.expires_at};}
function redeemVoucher_(ctx,p){assert_(limit_(ctx,'voucher.redeem:'+ctx.actor.id,60,3600),'RATE_LIMIT','Batas penebusan 60/jam.');var v=validateCode_(ctx,p),spend=num_(p.spend,0,100000000000);assert_(spend>=v.min_spend,'MIN_SPEND','Belanja belum mencapai minimum.');assert_(!ctx.table('Redemptions').some(function(r){return r.voucher_id===v.id;}),'ALREADY_REDEEMED','Voucher sudah digunakan.');var t=entity_(ctx,'VoucherTemplates',v.template_id),discount=v.type==='fixed'?Math.min(v.value,spend):v.type==='percent'?Math.round(spend*v.value/100):0;var r=ctx.add('Redemptions',{voucher_id:v.id,customer_id:v.customer_id,workshop_id:id_(p.workshop_id),user_id:ctx.actor.id,transaction_ref:str_(p.transaction_ref,150,true),spend:spend,discount_value:discount,estimated_cost:discount||t.cost||0},v.id);v.status='redeemed';v.redeemed_at=now_();ctx.put('Vouchers',v);creditPoints_(ctx,v.customer_id,'voucher_redeemed',r.id,0);audit_(ctx,'voucher.redeem','Vouchers',v.id,{workshop_id:r.workshop_id,spend:spend});return {id:r.id,code:v.code,status:'redeemed',discount_value:discount};}
function voidVoucher_(ctx,p){var v=entity_(ctx,'Vouchers',id_(p.voucher_id));assert_(v.status!=='redeemed','CONFLICT','Voucher redeemed tidak dapat void.');v.status='void';v.void_reason=str_(p.reason,500,true);ctx.put('Vouchers',v);audit_(ctx,'voucher.void','Vouchers',v.id,{reason:v.void_reason});return {id:v.id,status:v.status};}
function sendVoucher_(ctx,p){var v=entity_(ctx,'Vouchers',id_(p.voucher_id));assert_(v.approval_status==='approved'&&['issued','sent','delivered'].indexOf(v.status)!==-1&&Date.parse(v.expires_at)>Date.now(),'VALIDATION','Voucher harus aktif dan disetujui.');var m=enqueueMessage_(ctx,v.customer_id,'voucher_issued',{voucher_id:v.id,dedupe_key:'voucher:'+v.id});v.message_id=m.id;ctx.put('Vouchers',v);return messagePublic_(m);}
function exportCustomer_(ctx,p){var c=entity_(ctx,'Customers',id_(p.customer_id)),data={customer:c};['Consents','PointsLedger','Vouchers','Redemptions','ServiceEvents','MessageLog'].forEach(function(t){data[t]=ctx.table(t).filter(function(r){return r.customer_id===c.id;});});return {filename:'TRW_customer_'+c.id+'.json',mime:'application/json',content:JSON.stringify(data,null,2)};}
function deleteCustomer_(ctx,p){var c=entity_(ctx,'Customers',id_(p.customer_id));var old=c.id;cancelPendingMessages_(ctx,old);['Consents','PointsLedger','Vouchers','Redemptions','ServiceEvents','MessageLog'].forEach(function(t){ctx.table(t).filter(function(r){return r.customer_id===old;}).forEach(function(r){r.customer_id='erased';if(t==='Consents'){r.evidence='Erased by data subject request';r.number_hash='';}if(t==='MessageLog'){r.variables={};r.manual_url='';r.error='';}ctx.put(t,r);});});ctx.table('Surveys').filter(function(s){return s.customer_id===old;}).forEach(function(s){s.customer_id='';ctx.put('Surveys',s);});ctx.table('LeadContacts').filter(function(r){return r.phone===c.phone;}).forEach(function(r){ctx.erase('LeadContacts',[r.id]);});ctx.table('Requests').filter(function(r){return r.status==='done'&&(r.response_json.indexOf(old)!==-1||r.response_json.indexOf(c.phone)!==-1||r.response_json.indexOf(c.phone.slice(1))!==-1);}).forEach(function(r){r.response_json=JSON.stringify({redacted:true,reason:'data subject erasure'});ctx.put('Requests',r);});ctx.erase('Customers',[old]);var job=ctx.add('PrivacyJobs',{customer_id:'erased',operation:'delete',status:'completed',requested_by:ctx.actor.id,completed_at:now_()},old);audit_(ctx,'customer.delete','PrivacyJobs',job.id,{erased:true});return {deleted:true,notice:'Customer registry and linked PII erased. Independent LeadContacts require separate retention/erasure. Drive evidence/exports/backups managed by owner.'};}
