function reminderStage_(customer,date,logs){if(!customer.wa_opt_in||customer.deleted||customer.reminder_attempts>=3)return null;var delta=dayDiff_(date,customer.next_service_date),stage=delta>=14?'t_plus14':delta>=0?'t0':delta>=-14?'t_minus14':null;if(!stage)return null;return logs.some(function(m){return m.customer_id===customer.id&&m.cycle_id===customer.cycle_id&&m.stage===stage;})?null:stage;}
function runDailyReminders(){var props=PropertiesService.getScriptProperties(),conf=config_();if(!inQuietWindow_(conf))return {deferred:'quiet_hours'};var date=today_(),saved={date:date,cursor:0};try{var parsed=JSON.parse(props.getProperty('REMINDER_CURSOR')||'{}');if(parsed.date===date)saved=parsed;}catch(e){}
  var result=transaction_({id:'system',role:'admin'},{action:'internal.reminders',requestId:'reminders-'+date+'-'+saved.cursor,payload:{date:date,cursor:saved.cursor}},function(ctx){var customers=ctx.table('Customers').filter(function(c){return !c.deleted;}).sort(function(a,b){return a.id.localeCompare(b.id);}),batch=customers.slice(saved.cursor,saved.cursor+Math.min(50,conf.reminder_batch)),enqueued=0,start=Date.now(),done=0;
    for(var i=0;i<batch.length;i++){if(Date.now()-start>240000)break;var c=batch[i],stage=reminderStage_(c,date,ctx.table('MessageLog'));done++;if(!stage||frequencyBlocked_(ctx,c.id,''))continue;var tpl=stage==='t_plus14'?'win_back':'service_reminder',voucherId='',voucherTemplate=stage==='t_plus14'?conf.voucher_winback:stage==='t_minus14'?conf.voucher_t14:'';
      if(voucherTemplate){try{voucherId=issueVoucherFor_(ctx,c.id,voucherTemplate,'reminder:'+c.cycle_id+':'+stage).id;}catch(e){if(['QUOTA_EXCEEDED','VALIDATION'].indexOf(e.code)===-1)throw e;}}
      enqueueMessage_(ctx,c.id,tpl,{cycle_id:c.cycle_id,stage:stage,voucher_id:voucherId,dedupe_key:'reminder:'+c.id+':'+c.cycle_id+':'+stage});c.reminder_attempts++;ctx.put('Customers',c);enqueued++;
    }
    return {cursor:saved.cursor+done,total:customers.length,enqueued:enqueued,done:saved.cursor+done>=customers.length,date:date};});
  var lock=LockService.getScriptLock();lock.waitLock(15000);try{props.setProperty('REMINDER_CURSOR',JSON.stringify({date:date,cursor:result.cursor,done:result.done}));}finally{lock.releaseLock();}return result;
}
function audience_(ctx,filter){var conf=config_(ctx);return ctx.table('Customers').filter(function(c){if(c.deleted||!c.wa_opt_in)return false;if(filter.workshop_id&&c.workshop_id!==filter.workshop_id)return false;if(filter.tier&&tier_(pointsBalance_(ctx,c.id),conf)!==filter.tier)return false;if(filter.service_type&&c.service_type!==filter.service_type)return false;if(filter.overdue_days!==undefined&&dayDiff_(today_(),c.next_service_date)<filter.overdue_days)return false;if(filter.birthday_today&&c.birthday.slice(5)!==today_().slice(5))return false;return true;}).sort(function(a,b){return a.id.localeCompare(b.id);});}
function campaignInput_(p){var a=p.audience||{};assert_(typeof a==='object'&&!Array.isArray(a),'VALIDATION','Audience object diperlukan.');var allowed=['workshop_id','tier','service_type','overdue_days','birthday_today'];Object.keys(a).forEach(function(k){assert_(allowed.indexOf(k)!==-1,'VALIDATION','Filter tidak dikenal.');});if(a.workshop_id)id_(a.workshop_id);if(a.tier)one_(a.tier,['Silver','Gold','Platinum']);if(a.service_type)one_(a.service_type,['general','brake_check','shock_absorber']);if(a.overdue_days!==undefined)num_(a.overdue_days,0,3650);if(a.birthday_today!==undefined)bool_(a.birthday_today);return a;}
function saveCampaign_(ctx,p){var c=p.id?entity_(ctx,'Campaigns',id_(p.id)):ctx.add('Campaigns',{cursor:0,cycle_key:uuid_(),audience_ids:[]},'campaign'),status=one_(p.status,['draft','scheduled','paused']);if(c.status==='completed'&&status==='draft'){c.cycle_key=uuid_();c.cursor=0;c.audience_ids=[];}var changed=c.cursor>0&&(JSON.stringify(c.audience)!==JSON.stringify(campaignInput_(p))||c.template!==p.template||c.voucher_template_id!==(p.voucher_template_id||''));if(changed){c.cycle_key=uuid_();c.cursor=0;c.audience_ids=[];}Object.assign(c,{name:str_(p.name,150,true),audience:campaignInput_(p),template:one_(p.template,['voucher_issued','service_reminder','win_back']),voucher_template_id:p.voucher_template_id?id_(p.voucher_template_id):'',scheduled_at:iso_(p.scheduled_at),status:status});if(c.voucher_template_id)entity_(ctx,'VoucherTemplates',c.voucher_template_id);ctx.put('Campaigns',c);audit_(ctx,'campaign.save','Campaigns',c.id,{status:status});return c;}
function previewCampaign_(ctx,p){var c=p.campaign_id?entity_(ctx,'Campaigns',id_(p.campaign_id)):{audience:campaignInput_(p),template:one_(p.template,['voucher_issued','service_reminder','win_back'])},rows=audience_(ctx,c.audience),conf=config_(ctx);return {count:rows.length,quietHours:!inQuietWindow_(conf),customers:rows.slice(0,100).map(function(row){return {id:row.id,name:row.name,phone_mask:'•••'+row.phone.slice(-4),workshop_id:row.workshop_id,capped:frequencyBlocked_(ctx,row.id,''),preview:renderMessage_(conf['template_'+c.template],variables_(ctx,row,null))};}),truncated:rows.length>100,dryRun:true};}
function runCampaign_(ctx,p){var c=entity_(ctx,'Campaigns',id_(p.campaign_id));assert_(c.status==='scheduled'||c.status==='running','VALIDATION','Campaign harus scheduled/running. Pause/resume dengan campaign.save.');if(Date.parse(c.scheduled_at)>Date.now())return {deferred:true};if(!c.audience_ids||!c.audience_ids.length&&c.cursor===0)c.audience_ids=audience_(ctx,c.audience).map(function(row){return row.id;});var rows=c.audience_ids,batch=rows.slice(c.cursor,c.cursor+Math.min(50,config_(ctx).reminder_batch)),enqueued=0;batch.forEach(function(customerId){var row=ctx.table('Customers').find(function(c){return c.id===customerId;});if(!row||!row.wa_opt_in||row.deleted)return;var key='campaign:'+c.id+':'+c.cycle_key+':'+row.id;if(ctx.table('MessageLog').some(function(m){return m.dedupe_key===key;}))return;var voucher='';if(c.voucher_template_id){try{voucher=issueVoucherFor_(ctx,row.id,c.voucher_template_id,key).id;}catch(e){if(['QUOTA_EXCEEDED','VALIDATION'].indexOf(e.code)!==-1)return;throw e;}}enqueueMessage_(ctx,row.id,c.template,{campaign_id:c.id,campaign_cycle_id:c.cycle_key,voucher_id:voucher,dedupe_key:key});enqueued++;});c.cursor+=batch.length;c.status=c.cursor>=rows.length?'completed':'running';ctx.put('Campaigns',c);return {id:c.id,enqueued:enqueued,cursor:c.cursor,total:rows.length,status:c.status};}
function testCampaign_(ctx,p){var phone=phone_(p.phone);assert_(p.confirm_own_number===true,'CONSENT_REQUIRED','Konfirmasi nomor test adalah nomor Anda sendiri.');var template=one_(p.template,['voucher_issued','service_reminder','win_back']),existing=ctx.table('Customers').find(function(c){return c.phone===phone&&c.plate==='B9999TST';}),workshop=id_(p.workshop_id);entity_(ctx,'Outlets',workshop);var c=existing||ctx.add('Customers',{name:'Test Admin',phone:phone,plate:'B9999TST',brand:'Test',model:'Test',year:Number(today_().slice(0,4)),workshop_id:workshop,last_service_date:today_(),next_service_date:addMonths_(today_(),6),service_type:'general',cycle_id:uuid_(),reminder_attempts:0,deleted:false},'test-admin');consent_(ctx,c,true,'workshop','Admin explicitly confirmed own-number test');ctx.put('Customers',c);var m=enqueueMessage_(ctx,c.id,template,{dedupe_key:'test:'+ctx.requestId});return messagePublic_(m);}
function runBackgroundJobs(){var start=Date.now(),props=PropertiesService.getScriptProperties(),cursor;try{cursor=JSON.parse(props.getProperty('REMINDER_CURSOR')||'{}');}catch(e){cursor={};}if(cursor.date===today_()&&!cursor.done)runDailyReminders();if(Date.now()-start<240000){var campaigns=readTable_('Campaigns',false).filter(function(c){return ['scheduled','running'].indexOf(c.status)!==-1&&Date.parse(c.scheduled_at)<=Date.now();});for(var j=0;j<campaigns.length&&Date.now()-start<240000;j++){var c=campaigns[j];transaction_({id:'system',role:'admin'},{action:'internal.campaign',requestId:'campaign-'+c.id+'-'+c.cycle_key+'-'+c.cursor,payload:{campaign_id:c.id}},function(ctx){return runCampaign_(ctx,{campaign_id:c.id});});}}
  var messages=readTable_('MessageLog',false).filter(function(m){return ['queued','retry'].indexOf(m.status)!==-1&&Date.parse(m.next_retry_at)<=Date.now();});for(var i=0;i<messages.length&&i<25&&Date.now()-start<260000;i++)processMessage_(messages[i].id);
  // Interrupted external sends are ambiguous. Do not automatically send them again.
  transaction_({id:'system',role:'admin'},{action:'internal.maintenance',requestId:'maintenance-'+today_()+'-'+Math.floor(Date.now()/900000),payload:{}},function(ctx){var count=0;ctx.table('MessageLog').filter(function(m){return m.status==='sending'&&Date.now()-Date.parse(m.last_attempt_at)>10*60000;}).forEach(function(m){m.status='unknown';m.error='Interrupted provider request; verify in provider dashboard.';ctx.put('MessageLog',m);count++;});ctx.table('Vouchers').filter(function(v){return ['issued','sent','delivered'].indexOf(v.status)!==-1&&Date.parse(v.expires_at)<Date.now();}).forEach(function(v){v.status='expired';ctx.put('Vouchers',v);});return {ambiguous:count};});
}
function installTriggers(){var lock=LockService.getScriptLock();lock.waitLock(15000);try{ScriptApp.getProjectTriggers().filter(function(t){return ['runDailyReminders','runBackgroundJobs'].indexOf(t.getHandlerFunction())!==-1;}).forEach(function(t){ScriptApp.deleteTrigger(t);});ScriptApp.newTrigger('runDailyReminders').timeBased().atHour(9).nearMinute(0).everyDays(1).inTimezone(TZ_).create();ScriptApp.newTrigger('runBackgroundJobs').timeBased().everyMinutes(15).create();return {installed:2,timezone:TZ_,daily:'around 09:00 (Google time triggers are approximate)',continuation:'every 15 minutes'};}finally{lock.releaseLock();}}
