function accepted_(ctx,v){if(v.status==='approved')return taskComplete_(ctx,v);if(v.status==='client-approved exception'){var e=ctx.table('Exceptions').find(function(r){return r.id===v.exception_id;});return !!(e&&e.status==='client-approved exception'&&e.approval_note&&evidence_(ctx,v).exception);}return false;}
function qualified_(l){return !!(l.category&&l.need&&l.contact_permission&&l.recipient_id);}
function verified_(l){return !!(l.outcome==='sale'&&l.verified_at&&l.verified_by&&l.transaction_ref);}
function reportKpi_(ctx,p){var conf=config_(ctx),scope=ctx.actor.role==='spg'||ctx.actor.role==='fm',from=p.from?date_(p.from):'',to=p.to?date_(p.to):'';assert_(!from||!to||from<=to,'VALIDATION','Rentang tanggal tidak valid.');var match=function(r,d){return (!scope||r.user_id===ctx.actor.id)&&(!from||d>=from)&&(!to||d<=to);};
  var visits=ctx.table('Visits').filter(function(v){return match(v,v.date);}),accepted=visits.filter(function(v){return accepted_(ctx,v);}),fm=accepted.filter(function(v){return v.kind==='fm';}),spg=accepted.filter(function(v){return v.kind==='spg'&&v.status==='approved';}),rot=ctx.table('Rotation').filter(function(r){return match(r,r.week_start);}),survey=ctx.table('Surveys').filter(function(s){return match(s,day_(s.created_at));}),valid=survey.filter(function(s){return s.status==='valid'&&s.eligible&&s.consent&&s.required_complete;});var groups={};valid.forEach(function(s){var k=s.outlet_id+':'+s.week;groups[k]=(groups[k]||0)+1;});var leads=ctx.table('Leads').filter(function(l){return match(l,day_(l.created_at));});
  var trend={};visits.forEach(function(v){if(!trend[v.date])trend[v.date]={date:v.date,submitted:0,accepted:0,exceptions:0};if(v.status!=='draft')trend[v.date].submitted++;if(accepted_(ctx,v))trend[v.date].accepted++;if(v.exception_id)trend[v.date].exceptions++;});var drivers={};var validIds=new Set(valid.map(function(s){return s.id;}));ctx.table('SurveyAnswers').filter(function(a){return validIds.has(a.survey_id);}).forEach(function(a){drivers[a.decision_driver]=(drivers[a.decision_driver]||0)+1;});
  var fmTarget=scope&&ctx.actor.role==='fm'?480:2400,threshold=scope&&ctx.actor.role==='fm'?456:2280;
  return {scope:scope?'personal':'pilot',period:{from:from,to:to},options:{spg:conf.option_spg,fm:conf.option_fm},
    spg:{filledShifts:new Set(spg.map(function(v){return v.assignment_id;})).size,plannedShifts:rot.length,uniqueWorkshops:new Set(spg.map(function(v){return v.outlet_id;})).size,workshopTarget:scope?16:80,validSurveys:valid.length,surveyTarget:scope?160:800,workshopWeeksMeeting10:Object.values(groups).filter(function(n){return n>=10;}).length,workshopWeekCounts:Object.keys(groups).map(function(k){return {key:k,count:groups[k]};})},
    fm:{acceptedVisits:fm.length,target:fmTarget,threshold:threshold,pilotTarget:2400,pilotThreshold:2280,coveragePct:Math.round(fm.length/fmTarget*10000)/100,meets95:fm.length>=threshold,uniqueOutlets:new Set(fm.map(function(v){return v.outlet_id;})).size,uniqueOutletsDefinition:'Satu lokasi fisik, satu ID outlet deduplikasi.'},
    quality:{submitted:visits.filter(function(v){return v.status!=='draft';}).length,accepted:accepted.length,pending:visits.filter(function(v){return v.status==='pending';}).length,rejected:visits.filter(function(v){return v.status==='rejected';}).length,gpsFlags:visits.filter(function(v){return v.gps_flags.length>0;}).length,backChecks:visits.filter(function(v){return v.backcheck;}).length,clientApprovedExceptions:accepted.filter(function(v){return v.status==='client-approved exception';}).length},
    learning:{recordedLeads:leads.length,qualifiedOpportunities:leads.filter(qualified_).length,acknowledged:leads.filter(function(l){return !!l.ack_at;}).length,verifiedSales:leads.filter(verified_).length,verifiedSalesValue:leads.filter(verified_).reduce(function(n,l){return n+l.sale_value;},0),overdueHandOff:leads.filter(function(l){return l.status==='validated'&&Date.parse(l.sla_due_at)<Date.now();}).length,claim:'Data pilot. Sales hanya outcome terkonfirmasi; tanpa klaim uplift.'},
    loyalty:loyaltyKpi_(ctx,scope),trend:Object.values(trend).sort(function(a,b){return a.date.localeCompare(b.date);}),decisionDrivers:drivers,generatedAt:now_()};
}
function loyaltyKpi_(ctx,personal){if(personal)return {restricted:true};var msgs=ctx.table('MessageLog'),vouchers=ctx.table('Vouchers'),red=ctx.table('Redemptions'),events=ctx.table('ServiceEvents'),rem=msgs.filter(function(m){return m.stage&&['sent','delivered'].indexOf(m.status)!==-1;}),contacted=new Set(rem.map(function(m){return m.customer_id;})),returns=events.filter(function(e){return e.kind==='visit'&&e.reminder_id&&contacted.has(e.customer_id);}),back=new Set(returns.map(function(e){return e.customer_id;})),workshops={};rem.forEach(function(m){var c=ctx.table('Customers').find(function(c){return c.id===m.customer_id;});if(c){if(!workshops[c.workshop_id])workshops[c.workshop_id]={workshop_id:c.workshop_id,contacted:new Set(),returned:new Set()};workshops[c.workshop_id].contacted.add(c.id);}});returns.forEach(function(e){if(workshops[e.workshop_id])workshops[e.workshop_id].returned.add(e.customer_id);});return {sent:msgs.filter(function(m){return m.sent_at;}).length,delivered:msgs.filter(function(m){return m.delivered_at;}).length,failed:msgs.filter(function(m){return m.status==='failed'||m.status==='unknown';}).length,manualPending:msgs.filter(function(m){return m.status==='manual_pending';}).length,issued:vouchers.length,redeemed:red.length,redemptionRate:vouchers.length?Math.round(red.length/vouchers.length*10000)/100:0,returnVisitRate:contacted.size?Math.round(back.size/contacted.size*10000)/100:0,voucherCost:red.reduce(function(n,r){return n+r.estimated_cost;},0),redeemedDiscountValue:red.reduce(function(n,r){return n+r.discount_value;},0),redeemedTransactionValue:red.reduce(function(n,r){return n+r.spend;},0),workshops:Object.values(workshops).map(function(w){return {workshop_id:w.workshop_id,contacted:w.contacted.size,returned:w.returned.size,returnVisitRate:w.contacted.size?Math.round(w.returned.size/w.contacted.size*10000)/100:0,repeatVisitLift:null,liftNote:'Baseline terkonfirmasi diperlukan; lift belum dihitung.'};}),label:'Data pilot, bukan ROI terjamin. Return hanya service event terverifikasi setelah pesan.'};}
function exportReport_(ctx,p){var type=one_(p.type,['kpi','visits','leads','surveys']);if(ctx.actor.role==='client_viewer')assert_(type==='kpi','FORBIDDEN','Client hanya ekspor KPI agregat.');var rows,cols;if(type==='kpi'){var k=reportKpi_(ctx,p);rows=[{fm_accepted:k.fm.acceptedVisits,fm_target:2400,fm_threshold:2280,fm_coverage_pct:k.fm.coveragePct,unique_outlets:k.fm.uniqueOutlets,spg_filled:k.spg.filledShifts,spg_planned:k.spg.plannedShifts,unique_workshops:k.spg.uniqueWorkshops,valid_surveys:k.spg.validSurveys,qualified_opportunities:k.learning.qualifiedOpportunities,verified_sales:k.learning.verifiedSales,verified_sales_value:k.learning.verifiedSalesValue}];cols=Object.keys(rows[0]);}else{rows=ctx.table(type==='visits'?'Visits':type==='leads'?'Leads':'Surveys');cols=type==='visits'?['id','date','user_id','outlet_id','kind','status','distance_m','accuracy','gps_flags']:type==='leads'?['id','outlet_id','category','status','validated_at','sla_due_at','ack_at','outcome','verified_at','sale_value']:['id','outlet_id','week','status','consent','eligible'];}return {filename:'TRW_'+type+'_'+today_()+'.csv',mime:'text/csv;charset=utf-8',content:csv_(rows,cols)};}
