var ALL_ROLES_=['spg','fm','supervisor','client_viewer','admin'];
var FIELD_ROLES_=['spg','fm','supervisor','admin'];
var MANAGERS_=['supervisor','admin'];
var ROUTES_={
 'auth.login':{roles:['anonymous'],write:true,fn:login_},
 'auth.logout':{roles:ALL_ROLES_,write:true,fn:logout_},
 'me.today':{roles:ALL_ROLES_,fn:todayData_},
 'me.bootstrap':{roles:ALL_ROLES_,fn:bootstrap_},
 'visit.start':{roles:['spg','fm'],write:true,fn:startVisit_},
 'visit.submit':{roles:['spg','fm'],write:true,fn:submitVisit_},
 'visit.review':{roles:MANAGERS_,write:true,fn:reviewVisit_},
 'photo.upload':{roles:['spg','fm'],write:true,fn:uploadPhoto_},
 'photo.read':{roles:FIELD_ROLES_,fn:readPhoto_},
 'survey.submit':{roles:['spg'],write:true,fn:submitSurvey_},
 'survey.review':{roles:MANAGERS_,write:true,fn:reviewSurvey_},
 'lead.create':{roles:['spg','fm'],write:true,fn:createLead_},
 'lead.update':{roles:['supervisor','admin','client_viewer'],write:true,fn:updateLead_},
 'lead.list':{roles:ALL_ROLES_,fn:listLeads_},
 'lead.contacts':{roles:MANAGERS_,fn:leadContacts_},
 'training.list':{roles:ALL_ROLES_,fn:trainingList_},
 'training.submit':{roles:['spg','fm'],write:true,fn:submitTraining_},
 'training.practical':{roles:MANAGERS_,write:true,fn:practical_},
 'training.save':{roles:['admin'],write:true,fn:saveTraining_},
 'report.kpi':{roles:ALL_ROLES_,fn:reportKpi_},
 'report.export':{roles:['supervisor','admin','client_viewer'],fn:exportReport_},
 'customer.upsert':{roles:FIELD_ROLES_,write:true,fn:upsertCustomer_},
 'customer.list':{roles:FIELD_ROLES_,fn:listCustomers_},
 'customer.optout':{roles:MANAGERS_,write:true,fn:optoutCustomer_},
 'customer.service':{roles:MANAGERS_.concat(['client_viewer']),write:true,fn:serviceCustomer_},
 'customer.export':{roles:['admin'],fn:exportCustomer_},
 'customer.delete':{roles:['admin'],write:true,fn:deleteCustomer_},
 'voucher.templates':{roles:ALL_ROLES_,fn:function(ctx){return ctx.table('VoucherTemplates').filter(function(t){return t.active;});}},
 'voucher.template.save':{roles:['admin'],write:true,fn:saveVoucherTemplate_},
 'voucher.issue':{roles:FIELD_ROLES_,write:true,fn:issueVoucher_},
 'voucher.approve':{roles:['client_viewer','admin'],write:true,fn:approveVoucher_},
 'voucher.list':{roles:ALL_ROLES_,fn:listVouchers_},
 'voucher.send':{roles:MANAGERS_,write:true,fn:sendVoucher_},
 'voucher.validate':{roles:FIELD_ROLES_,fn:validateVoucher_},
 'voucher.redeem':{roles:FIELD_ROLES_,write:true,fn:redeemVoucher_},
 'voucher.void':{roles:MANAGERS_,write:true,fn:voidVoucher_},
 'campaign.save':{roles:['admin'],write:true,fn:saveCampaign_},
 'campaign.preview':{roles:['admin'],fn:previewCampaign_},
 'campaign.run':{roles:['admin'],write:true,fn:runCampaign_},
 'campaign.test':{roles:['admin'],write:true,fn:testCampaign_},
 'campaign.list':{roles:['admin'],fn:function(ctx){return ctx.table('Campaigns');}},
 'message.open':{roles:MANAGERS_,write:true,fn:manualOpen_},
 'message.status':{roles:MANAGERS_,write:true,fn:manualMessageStatus_},
 'message.list':{roles:MANAGERS_,fn:listMessages_},
 'admin.setup':{roles:['admin'],fn:function(){return {ready:true,notice:'Run setup() in editor for idempotent schema checks.'};}},
 'admin.config':{roles:['admin'],write:true,fn:saveConfig_},
 'admin.user':{roles:['admin'],write:true,fn:saveUser_},
 'admin.outlet':{roles:['admin'],write:true,fn:saveOutlet_},
 'admin.list':{roles:MANAGERS_,fn:adminList_},
 'rotation.generate':{roles:['admin'],write:true,fn:generateRotation_},
 'roster.generate':{roles:MANAGERS_,write:true,fn:generateRoster_},
 'roster.rebook':{roles:MANAGERS_,write:true,fn:rebookRoster_}
};
