function saveOutlet_(ctx,p){var r=p.id?entity_(ctx,'Outlets',id_(p.id)):ctx.add('Outlets',{},str_(p.physical_key,100,true)),key=str_(p.physical_key,100,true).toLowerCase();assert_(!ctx.table('Outlets').some(function(o){return o.id!==r.id&&o.physical_key===key;}),'DUPLICATE','Lokasi fisik sudah terdaftar.');Object.assign(r,{name:str_(p.name,150,true),physical_key:key,area:str_(p.area,100,true),address:str_(p.address,500,true),lat:num_(p.lat,-90,90),lng:num_(p.lng,-180,180),active:bool_(p.active),booking_url:url_(p.booking_url),contact_label:str_(p.contact_label,100)});ctx.put('Outlets',r);if(p.workshop===true){var w=ctx.table('Workshops').find(function(x){return x.outlet_id===r.id;})||ctx.add('Workshops',{outlet_id:r.id},r.id);w.name=r.name;w.active=r.active;ctx.put('Workshops',w);}audit_(ctx,'outlet.save','Outlets',r.id,{});return r;}
function eligibleStaff_(ctx,role,ids){var users=ctx.table('Users').filter(function(u){return u.active&&u.role===role&&(!ids||ids.indexOf(u.id)!==-1);});assert_(users.length>0,'NOT_READY','Tidak ada staf aktif.');users.forEach(function(u){assert_(readiness_(ctx,u.id),'NOT_READY',u.name+' belum lulus quiz + praktik.');});return users;}
function generateRotation_(ctx,p){assert_(config_(ctx).option_spg,'OPTION_DISABLED','Opsi SPG tidak aktif.');var start=date_(p.start_date),staff=eligibleStaff_(ctx,'spg',listIds_(p.user_ids));assert_(staff.length===5,'VALIDATION','Rencana pilot memerlukan 5 SPG.');assert_(new Date(start+'T12:00:00+07:00').getUTCDay()===1,'VALIDATION','Tanggal awal rotasi harus Senin.');var workshops=ctx.table('Workshops').filter(function(w){return w.active;}).map(function(w){return entity_(ctx,'Outlets',w.outlet_id);}).filter(function(o){return o.active;});var ids=p.outlet_ids?listIds_(p.outlet_ids):workshops.map(function(w){return w.id;});assert_(ids.length===80&&ids.every(function(id){return workshops.some(function(o){return o.id===id;});}),'VALIDATION','Lengkapi dan pilih tepat 80 workshop unik.');
  assert_(!ctx.table('Rotation').some(function(r){return r.week_start<=addDays_(start,111)&&r.week_end>=start;}),'CONFLICT','Rencana rotasi periode ini sudah ada.');var sorted=ids.map(function(id){return entity_(ctx,'Outlets',id);}).sort(function(a,b){return (a.area+a.name).localeCompare(b.area+b.name);});
  for(var week=0;week<16;week++){for(var i=0;i<5;i++){ctx.add('Rotation',{user_id:staff[i].id,outlet_id:sorted[week*5+i].id,week:week+1,week_start:addDays_(start,week*7),week_end:addDays_(start,week*7+6),status:'planned',plan_id:ctx.requestId},week+'-'+i);}}
  audit_(ctx,'rotation.generate','Rotation',ctx.requestId,{workshops:80,weeks:16});return {assignments:80,workshops:80,blocks:4};
}
function nearestRoute_(outlets,lat,lng){var remaining=outlets.slice(),route=[];while(remaining.length){remaining.sort(function(a,b){return haversine_(lat,lng,a.lat,a.lng)-haversine_(lat,lng,b.lat,b.lng);});var next=remaining.shift();route.push(next);lat=next.lat;lng=next.lng;}return route;}
function generateRoster_(ctx,p){var conf=config_(ctx);assert_(conf.option_fm,'OPTION_DISABLED','Opsi FM tidak aktif.');var date=date_(p.date),staff=eligibleStaff_(ctx,'fm',listIds_(p.user_ids)),outlets=ctx.table('Outlets').filter(function(o){return o.active;});assert_(outlets.length>=staff.length*6+1,'VALIDATION','Perlu minimal '+(staff.length*6+1)+' outlet untuk 6 primer per FM tanpa duplikasi harian. Seed 20 cukup untuk maksimal 3 FM.');var used={};ctx.table('Roster').filter(function(r){return r.date===date&&!r.backup;}).forEach(function(r){used[r.outlet_id]=true;});var made=[];
  staff.forEach(function(u){assert_(!ctx.table('Roster').some(function(r){return r.user_id===u.id&&r.date===date;}),'CONFLICT','Roster '+u.name+' sudah ada untuk tanggal ini.');var local=outlets.filter(function(o){return o.area===u.area;}),base=local[0]||outlets[0],available=outlets.filter(function(o){return !used[o.id];}),ordered=nearestRoute_(available,base.lat,base.lng);assert_(ordered.length>=7,'VALIDATION','Outlet tidak cukup untuk primer + backup.');var primary=ordered.slice(0,6);primary.forEach(function(o){used[o.id]=true;});var last=primary[5],backup=outlets.filter(function(o){return primary.every(function(x){return x.id!==o.id;});}).sort(function(a,b){return haversine_(last.lat,last.lng,a.lat,a.lng)-haversine_(last.lat,last.lng,b.lat,b.lng);})[0];primary.concat([backup]).forEach(function(o,i){made.push(ctx.add('Roster',{user_id:u.id,outlet_id:o.id,date:date,position:i+1,backup:i===6,status:'planned',rebook_of:'',plan_id:ctx.requestId},u.id+'-'+i));});});audit_(ctx,'roster.generate','Roster',ctx.requestId,{date:date,count:made.length});return {assignments:made.length};}
function rebookRoster_(ctx,p){var ids=listIds_(p.roster_ids),date=date_(p.date);assert_(date>=today_(),'VALIDATION','Rebooking harus hari ini atau berikutnya.');var made=[];ids.forEach(function(id){var old=entity_(ctx,'Roster',id);assert_(!old.backup&&(old.status==='missed'||old.date<today_())&&old.status!=='completed'&&old.status!=='rebooked','VALIDATION','Hanya kunjungan primer yang belum selesai.');assert_(readiness_(ctx,old.user_id),'NOT_READY','Staf belum siap.');assert_(!ctx.table('Roster').some(function(r){return r.rebook_of===old.id;}),'CONFLICT','Sudah direbooking.');var slots=ctx.table('Roster').filter(function(r){return r.user_id===old.user_id&&r.date===date&&!r.backup;});assert_(slots.length<6,'VALIDATION','Roster tujuan sudah memiliki 6 primer.');made.push(ctx.add('Roster',{user_id:old.user_id,outlet_id:old.outlet_id,date:date,position:slots.length+1,backup:false,status:'planned',rebook_of:old.id,plan_id:ctx.requestId},old.id));old.status='rebooked';ctx.put('Roster',old);});audit_(ctx,'roster.rebook','Roster',ctx.requestId,{count:made.length});return {rebooked:made.length};}
