/** Run from editor, owner account. Non-destructive and idempotent. No Advanced APIs. */
function setup(){var lock=LockService.getScriptLock();lock.waitLock(20000);try{var p=PropertiesService.getScriptProperties(),ss=p.getProperty('SPREADSHEET_ID')?SpreadsheetApp.openById(p.getProperty('SPREADSHEET_ID')):SpreadsheetApp.getActiveSpreadsheet();if(!ss)ss=SpreadsheetApp.create('TRW Route to Preference — Pilot');p.setProperty('SPREADSHEET_ID',ss.getId());ss.setSpreadsheetTimeZone(TZ_);
  if(!p.getProperty('AUTH_PEPPER'))p.setProperty('AUTH_PEPPER',uuid_()+uuid_());if(!p.getProperty('WEBHOOK_SECRET'))p.setProperty('WEBHOOK_SECRET',uuid_()+uuid_());if(!p.getProperty('DRIVE_ROOT_ID'))p.setProperty('DRIVE_ROOT_ID',DriveApp.createFolder('TRW_Pilot').getId());
  Object.keys(COLUMNS_).forEach(function(name){var sh=ss.getSheetByName(name)||ss.insertSheet(name),headers=BASE_COLUMNS_.concat(COLUMNS_[name]);if(sh.getLastRow()===0){if(sh.getMaxColumns()<headers.length)sh.insertColumnsAfter(sh.getMaxColumns(),headers.length-sh.getMaxColumns());sh.getRange(1,1,1,headers.length).setValues([headers]);}else{assert_(JSON.stringify(sh.getRange(1,1,1,headers.length).getValues()[0])===JSON.stringify(headers),'SCHEMA_ERROR','Header '+name+' tidak cocok; tidak diubah.');}
    sh.setFrozenRows(1);sh.getRange(1,1,1,headers.length).setBackground('#202126').setFontColor('#ffffff').setFontWeight('bold');sh.getRange(1,1,sh.getMaxRows(),headers.length).setWrapStrategy(SpreadsheetApp.WrapStrategy.CLIP);
    Object.keys(ENUMS_).filter(function(k){return k.split('.')[0]===name;}).forEach(function(k){var col=headers.indexOf(k.split('.')[1])+1;sh.getRange(2,col,Math.max(1,sh.getMaxRows()-1),1).setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(ENUMS_[k],true).setAllowInvalid(false).build());});
    if(['Users','Sessions','LeadContacts','Customers','Consents','Requests','MessageLog'].indexOf(name)!==-1&&!sh.getProtections(SpreadsheetApp.ProtectionType.SHEET).length){var protection=sh.protect().setDescription('PII/internal: owner only. Sheet protection is not a privacy boundary.');protection.removeEditors(protection.getEditors());if(protection.canDomainEdit())protection.setDomainEdit(false);}
  });
  var owner={id:'system',role:'admin'},ctx=makeContext_(owner,'setup-v1');var existing=ctx.table('Config');Object.keys(DEFAULT_CONFIG_).forEach(function(k){if(!existing.some(function(r){return r.key===k;}))ctx.add('Config',{key:k,value:JSON.stringify(DEFAULT_CONFIG_[k]),description:'Default '+k},k);});applyOps_(ctx.ops());
  var readme=ss.getSheetByName('README')||ss.insertSheet('README');readme.clearContents();readme.getRange(1,1,10,2).setValues([
    ['TRW Route to Preference','1.0.0'],['Timezone','Asia/Jakarta'],['Owner-only database','Do not share this file with staff or client viewers; use app RBAC.'],['setup()','Idempotent, never clears data.'],['Admin','Set ADMIN_PIN (8–12 digits) in Script Properties; run createAdminAccount().'],['Demo','Set DEMO_MODE=true + DEMO_PIN; run seedDemoData(). Synthetic data only.'],['Photos','Private TRW_Pilot/yyyy-MM/outletId; API photo.read for authorized reviewers.'],['KPI','Accepted=approved tasks+evidence OR client-approved exception. Target FM 2400, threshold 2280.'],['Quota/retention','Archive monthly, retain request journals >= offline retry horizon.'],['Personal data','LeadContacts/Customers/Consents restricted; consent and deletion require governance.']
  ]);readme.setFrozenRows(1);readme.setColumnWidths(1,2,500);readme.getDataRange().setWrap(true);return {spreadsheetId:ss.getId(),driveRootId:p.getProperty('DRIVE_ROOT_ID')};
}finally{lock.releaseLock();}}
function createAdminAccount(){var pin=PropertiesService.getScriptProperties().getProperty('ADMIN_PIN');validatePin_(pin);var actor={id:'system',role:'admin'};return transaction_(actor,{action:'bootstrap',requestId:'bootstrap-admin-v1',payload:{}},function(ctx){var current=ctx.table('Users').find(function(u){return u.role==='admin'&&u.active;});if(current)return {username:current.username,exists:true};var salt=uuid_(),u=ctx.add('Users',{username:'admin',name:'Administrator ARAIA',role:'admin',active:true,pin_salt:salt,pin_hash:pinHash_(pin,salt),area:'Jabodetabek',workshop_ids:[]},'admin');return {username:u.username};});}
function seedDemoData(){var prop=PropertiesService.getScriptProperties();assert_(prop.getProperty('DEMO_MODE')==='true','DEMO_DISABLED','Set DEMO_MODE=true hanya pada database demo.');var pin=validatePin_(prop.getProperty('DEMO_PIN'));return transaction_({id:'system',role:'admin'},{action:'demo.seed',requestId:'demo-seed-v1',payload:{}},function(ctx){
  var users=[];['spg','fm'].forEach(function(role){for(var i=1;i<=5;i++){var salt=uuid_();users.push(ctx.add('Users',{username:role+i,name:role.toUpperCase()+' Demo '+i,role:role,pin_salt:salt,pin_hash:pinHash_(pin,salt),active:true,area:['Jakarta','Bogor','Depok','Tangerang','Bekasi'][i-1],workshop_ids:[]},role+i));}});
  ['supervisor','client_viewer'].forEach(function(role){var salt=uuid_();users.push(ctx.add('Users',{username:role==='client_viewer'?'client':role,name:role==='client_viewer'?'TRW Demo Recipient':'Supervisor Demo',role:role,pin_salt:salt,pin_hash:pinHash_(pin,salt),active:true,area:'Jabodetabek',workshop_ids:[]},role));});
  var locations=[[-6.2088,106.8456],[-6.5971,106.8060],[-6.4025,106.7942],[-6.1783,106.6319],[-6.2383,106.9756]],outlets=[];
  for(var j=0;j<20;j++){var group=j%5,coords=locations[group],o=ctx.add('Outlets',{name:'Bengkel Demo '+('0'+(j+1)).slice(-2),physical_key:'demo-location-'+j,area:['Jakarta','Bogor','Depok','Tangerang','Bekasi'][group],address:'ALAMAT SIMULASI — verifikasi sebelum pilot',lat:coords[0]+Math.floor(j/5)*0.002,lng:coords[1]+Math.floor(j/5)*0.002,active:true,booking_url:'https://www.google.com/maps?q='+coords.join(','),contact_label:'Booking bengkel'},'outlet-'+j);outlets.push(o);ctx.add('Workshops',{outlet_id:o.id,name:o.name,active:true},'workshop-'+j);}
  var course=ctx.add('Training',{name:'DEMO: Consent, bukti, dan keselamatan — ganti materi produk sebelum live',questions:[{question:'Boleh mengirim WA tanpa opt-in?',options:['Boleh','Tidak'],correct:1},{question:'Merchandising FM dilakukan kapan?',options:['Sebelum engage','Sesudah penutupan'],correct:0},{question:'Bukti foto harus?',options:['Foto asli sebelum/sesudah','Bebas'],correct:0},{question:'Voucher boleh ditebus dua kali?',options:['Ya','Tidak'],correct:1},{question:'Angka penjualan harus?',options:['Diasumsikan','Dikonfirmasi client/partner'],correct:1}],pass_score:80,active:true,approved:true,version:'demo-v1'},'training');
  users.filter(function(u){return u.role==='spg'||u.role==='fm';}).forEach(function(u){ctx.add('QuizResults',{user_id:u.id,training_id:course.id,training_version:course.version,score:100,answers:[1,0,0,1,1],pass:true,practical_pass:true,practical_by:'system',practical_at:now_()},'quiz-'+u.id);});
  for(var k=0;k<20;k++){var last=addDays_(today_(),-180+k*2),c=ctx.add('Customers',{name:'Pelanggan SIMULASI '+(k+1),phone:'+628100000'+('000'+k).slice(-4),plate:'B'+(1000+k)+'TRW',brand:'Demo',model:'Simulasi',year:2020,birthday:'1993-01-02',workshop_id:outlets[k].id,last_service_date:last,odometer:20000,service_type:'general',next_service_date:addMonths_(last,6),wa_opt_in:false,consent_at:now_(),consent_source:'workshop',cycle_id:'demo-cycle-'+k,reminder_attempts:0,deleted:false},'customer-'+k);ctx.add('Consents',{customer_id:c.id,opt_in:false,timestamp:now_(),source:'workshop',actor_id:'system',text_version:'wa-opt-in-v1',evidence:'Synthetic seed. NO consent to send.',number_hash:digest_(c.phone)},'consent-'+k);}
  [{name:'Cek Keselamatan Gratis',type:'free_check',value:0,min_spend:0,cost:0},{name:'Voucher TRW Rp50.000',type:'fixed',value:50000,min_spend:200000,cost:50000},{name:'Potongan TRW 10%',type:'percent',value:10,min_spend:200000,cost:0}].forEach(function(t,i){ctx.add('VoucherTemplates',Object.assign(t,{validity_days:30,eligible_workshops:[],quota:500,terms:'Data pilot. Tidak dapat diuangkan. Satu penggunaan.',active:true,approval_required:true}),'template-'+i);});
  // Ready-to-use daily demo assignments, 7 distinct outlets per FM (cross-user overlap is demo only).
  users.filter(function(u){return u.role==='fm';}).forEach(function(u,i){for(var v=0;v<7;v++){var out=outlets[(i*4+v)%20];ctx.add('Roster',{user_id:u.id,outlet_id:out.id,date:today_(),position:v+1,backup:v===6,status:'planned',rebook_of:'',plan_id:'demo'},'roster-'+i+'-'+v);}});
  users.filter(function(u){return u.role==='spg';}).forEach(function(u,i){ctx.add('Rotation',{user_id:u.id,outlet_id:outlets[i].id,week:1,week_start:today_(),week_end:addDays_(today_(),6),status:'planned',plan_id:'demo'},'rotation-'+i);});
  audit_(ctx,'demo.seed','Users','demo',{synthetic:true});return {users:12,outlets:20,customers:20,templates:3,notice:'All demo customers opted out; no automatic messages. Do not enable real gateways on seed numbers.'};});}
