function ownVisit_(ctx,id){var v=entity_(ctx,'Visits',id_(id));assert_(v.user_id===ctx.actor.id,'FORBIDDEN','Kunjungan bukan milik Anda.');return v;}
function outletAccess_(ctx,outletId){if(MANAGERS_.indexOf(ctx.actor.role)!==-1)return true;var a=ctx.table('Roster').concat(ctx.table('Rotation'));return a.some(function(r){return r.user_id===ctx.actor.id&&r.outlet_id===outletId;})||(ctx.actor.workshop_ids||[]).indexOf(outletId)!==-1;}
function startVisit_(ctx,p){var conf=config_(ctx),kind=ctx.actor.role;assert_(conf['option_'+kind],'OPTION_DISABLED','Opsi lapangan tidak aktif.');assert_(readiness_(ctx,ctx.actor.id),'NOT_READY','Lulus quiz dan praktik terlebih dahulu.');var date=date_(p.date),o=entity_(ctx,'Outlets',id_(p.outlet_id));assert_(o.active,'VALIDATION','Outlet tidak aktif.');var assignment=kind==='fm'?entity_(ctx,'Roster',id_(p.assignment_id)):entity_(ctx,'Rotation',id_(p.assignment_id));
  assert_(assignment.user_id===ctx.actor.id&&assignment.outlet_id===o.id,'FORBIDDEN','Penugasan tidak sesuai.');assert_(kind==='fm'?assignment.date===date:(date>=assignment.week_start&&date<=assignment.week_end),'VALIDATION','Tanggal di luar penugasan.');assert_(dayDiff_(today_(),date)>=0&&dayDiff_(today_(),date)<=31,'VALIDATION','Tanggal kunjungan harus hari ini atau maksimal 31 hari sebelumnya.');
  var visitId=id_(p.visit_id),existing=ctx.table('Visits').find(function(v){return v.id===visitId;});if(existing){assert_(existing.user_id===ctx.actor.id&&existing.assignment_id===assignment.id,'CONFLICT','ID kunjungan telah digunakan.');return {id:existing.id};}
  var same=ctx.table('Visits').find(function(v){return v.assignment_id===assignment.id&&v.date===date&&v.status!=='rejected';});assert_(!same,'CONFLICT','Penugasan ini sudah memiliki kunjungan.');
  var started=iso_(p.started_at);assert_(day_(started)===date,'VALIDATION','Waktu mulai tidak sesuai tanggal.');var gps=gps_(p.gps||{},o),v=ctx.add('Visits',Object.assign({id:visitId,user_id:ctx.actor.id,outlet_id:o.id,assignment_id:assignment.id,kind:kind,date:date,started_at:started,status:'draft',stock:[],permission:false,posm:false,planogram:false,backcheck:false},gps),visitId);return {id:v.id,gpsFlags:v.gps_flags,distanceM:v.distance_m};
}
function evidence_(ctx,v){var photos=ctx.table('VisitPhotos').filter(function(ph){return ph.visit_id===v.id&&ph.user_id===v.user_id;});return {before:photos.some(function(p){return p.kind==='before';}),after:photos.some(function(p){return p.kind==='after';}),exception:photos.some(function(p){return p.kind==='exception';}),count:photos.length};}
function taskComplete_(ctx,v){var e=evidence_(ctx,v);return v.permission&&v.posm&&v.planogram&&Array.isArray(v.stock)&&v.stock.length>0&&e.before&&e.after&&(v.kind!=='fm'||!!v.retailer_questions)&&!!v.next_action;}
function submitVisit_(ctx,p){var v=ownVisit_(ctx,p.visit_id);assert_(v.status==='draft','CONFLICT','Kunjungan sudah dikirim.');var exception=p.exception;
  if(exception){var reason=one_(exception.reason,['outlet_closed','no_permission','no_stock','other']),ev=evidence_(ctx,v);assert_(ev.exception,'EVIDENCE_REQUIRED','Foto pengecualian wajib.');var ex=ctx.add('Exceptions',{visit_id:v.id,reason:reason,note:str_(exception.note,1000,true),status:'pending'},v.id);v.exception_id=ex.id;v.next_action=str_(p.next_action,500,true);
  }else{
    v.permission=bool_(p.permission);v.posm=bool_(p.posm);v.planogram=bool_(p.planogram);assert_(Array.isArray(p.stock)&&p.stock.length>=1&&p.stock.length<=30,'VALIDATION','Isi minimal satu data stok.');v.stock=p.stock.map(function(s){return {sku:str_(s.sku,100,true),qty:num_(s.qty,0,100000)};});v.retailer_questions=str_(p.retailer_questions,1500,v.kind==='fm');v.competitor=str_(p.competitor,1000);v.interest=one_(p.interest,['none','low','medium','high']);v.next_action=str_(p.next_action,500,true);assert_(taskComplete_(ctx,v),'EVIDENCE_REQUIRED','Izin kerja, stok, POSM, planogram, dan foto sebelum/sesudah wajib sebelum CLOSE.');
  }
  v.status='pending';v.submitted_at=now_();ctx.put('Visits',v);audit_(ctx,'visit.submit','Visits',v.id,{exception:!!exception,gps_flags:v.gps_flags});return {id:v.id,status:v.status,gpsFlags:v.gps_flags};
}
function reviewVisit_(ctx,p){var v=entity_(ctx,'Visits',id_(p.visit_id));assert_(v.status==='pending'||v.status==='rejected','CONFLICT','Kunjungan tidak menunggu validasi.');var approve=bool_(p.approve),note=str_(p.note,1000,!!(v.gps_flags||[]).length||!approve);v.reviewer_id=ctx.actor.id;v.review_note=note;v.backcheck=bool_(p.backcheck||false);v.backcheck_note=str_(p.backcheck_note,1000,v.backcheck);
  if(approve){if(v.exception_id){var e=entity_(ctx,'Exceptions',v.exception_id);e.status='client-approved exception';e.reviewer_id=ctx.actor.id;e.approval_note=str_(p.client_approval_ref,500,true);ctx.put('Exceptions',e);v.status='client-approved exception';}else{assert_(taskComplete_(ctx,v),'EVIDENCE_REQUIRED','Bukti tugas tidak lengkap.');v.status='approved';}}
  else{v.status='rejected';if(v.exception_id){var ex=entity_(ctx,'Exceptions',v.exception_id);ex.status='rejected';ex.reviewer_id=ctx.actor.id;ctx.put('Exceptions',ex);}}
  ctx.put('Visits',v);var table=v.kind==='fm'?'Roster':'Rotation',assignment=entity_(ctx,table,v.assignment_id);if(v.kind==='fm')assignment.status=approve?'completed':'missed';else if(approve)assignment.status='active';ctx.put(table,assignment);audit_(ctx,'visit.review','Visits',v.id,{status:v.status,note:note});return {id:v.id,status:v.status};
}
function jpegSize_(bytes){var n=bytes.map(function(b){return (b+256)%256;});assert_(n[0]===255&&n[1]===216,'VALIDATION','Foto harus JPEG.');var i=2;while(i+8<n.length){if(n[i]!==255){i++;continue;}var marker=n[i+1];if(marker===217||marker===218)break;var len=n[i+2]*256+n[i+3];if([192,193,194,195,197,198,199,201,202,203,205,206,207].indexOf(marker)!==-1){return {height:n[i+5]*256+n[i+6],width:n[i+7]*256+n[i+8]};}assert_(len>=2,'VALIDATION','JPEG tidak valid.');i+=len+2;}fail_('VALIDATION','Dimensi JPEG tidak ditemukan.');}
function uploadPhoto_(ctx,p){var v=ownVisit_(ctx,p.visit_id);assert_(v.status==='draft','CONFLICT','Foto hanya untuk draft.');var kind=one_(p.kind,['before','after','exception']),photoId=id_(p.photo_id),encoded=str_(p.base64,1500000,true);assert_(!ctx.table('VisitPhotos').some(function(ph){return ph.id===photoId;}),'CONFLICT','ID foto sudah digunakan; retry harus memakai requestId semula.');assert_(/^[A-Za-z0-9+/=]+$/.test(encoded),'VALIDATION','Base64 tidak valid.');var bytes=Utilities.base64Decode(encoded);assert_(bytes.length<=1048576,'TOO_LARGE','Foto maksimal 1 MB.');var size=jpegSize_(bytes);assert_(Math.max(size.width,size.height)<=1280,'TOO_LARGE','Foto maksimal 1280 px.');assert_(ctx.table('VisitPhotos').filter(function(r){return r.visit_id===v.id;}).length<8,'RATE_LIMIT','Maksimal 8 foto per kunjungan.');
  var month=day_(v.started_at).slice(0,7),folder=folderByName_(folderByName_(rootFolder_(),month),v.outlet_id),filename=photoId+'.jpg',it=folder.getFilesByName(filename),file=it.hasNext()?it.next():folder.createFile(Utilities.newBlob(bytes,'image/jpeg',filename));
  var ph=ctx.add('VisitPhotos',{id:photoId,visit_id:v.id,outlet_id:v.outlet_id,user_id:ctx.actor.id,kind:kind,file_id:file.getId(),url:file.getUrl(),bytes:bytes.length,captured_at:iso_(p.captured_at)},photoId);return {id:ph.id,fileId:ph.file_id,url:ph.url};
}
function readPhoto_(ctx,p){var ph=entity_(ctx,'VisitPhotos',id_(p.photo_id));assert_(MANAGERS_.indexOf(ctx.actor.role)!==-1||ph.user_id===ctx.actor.id,'FORBIDDEN','Foto tidak dapat diakses.');var f=DriveApp.getFileById(ph.file_id);return {id:ph.id,mime:'image/jpeg',base64:Utilities.base64Encode(f.getBlob().getBytes())};}
function submitSurvey_(ctx,p){var v=ownVisit_(ctx,p.visit_id);assert_(v.kind==='spg'&&(v.status==='pending'||v.status==='approved'),'VALIDATION','Survey harus terkait kunjungan SPG dengan bukti.');assert_(p.eligible===true&&p.consent===true,'CONSENT_REQUIRED','Responden harus eligible dan memberikan persetujuan sukarela.');var a=p.answers||{},ref=str_(a.respondent_ref,100,true);assert_(!ctx.table('SurveyAnswers').some(function(r){return r.respondent_ref===ref&&ctx.table('Surveys').some(function(s){return s.id===r.survey_id&&s.outlet_id===v.outlet_id&&s.week===entity_(ctx,'Rotation',v.assignment_id).week;});}),'DUPLICATE','Responden sudah mengisi untuk workshop-week ini.');
  var driver=one_(a.decision_driver,['safety','quality','price','mechanic_recommendation','availability','brand','other']),brand=str_(a.brand_preference,100,true),confidence=num_(a.confidence,1,5),need=str_(a.need,500,true),c=p.customer_id?entity_(ctx,'Customers',id_(p.customer_id)):null;if(c)assert_(c.workshop_id===v.outlet_id&&outletAccess_(ctx,c.workshop_id),'FORBIDDEN','Pelanggan tidak sesuai bengkel.');
  var s=ctx.add('Surveys',{user_id:ctx.actor.id,outlet_id:v.outlet_id,visit_id:v.id,week:entity_(ctx,'Rotation',v.assignment_id).week,eligible:true,consent:true,consent_at:iso_(p.consent_at),required_complete:true,status:'pending',customer_id:c?c.id:''},ref);ctx.add('SurveyAnswers',{survey_id:s.id,decision_driver:driver,brand_preference:brand,confidence:confidence,need:need,respondent_ref:ref},s.id);return {id:s.id,status:s.status};
}
function reviewSurvey_(ctx,p){var s=entity_(ctx,'Surveys',id_(p.survey_id));assert_(s.status==='pending','CONFLICT','Survey sudah divalidasi.');var valid=bool_(p.valid),v=entity_(ctx,'Visits',s.visit_id);assert_(!valid||(s.eligible&&s.consent&&s.required_complete&&v.status==='approved'),'VALIDATION','Kunjungan dan semua syarat survey harus lolos.');s.status=valid?'valid':'rejected';s.reviewer_id=ctx.actor.id;s.review_note=str_(p.note,1000,!valid);ctx.put('Surveys',s);var conf=config_(ctx);if(valid&&s.customer_id&&conf.voucher_after_survey){issueVoucherFor_(ctx,s.customer_id,conf.voucher_after_survey,'survey:'+s.id);}audit_(ctx,'survey.review','Surveys',s.id,{status:s.status});return {id:s.id,status:s.status};}
