function inQuietWindow_(conf,date){var hour=Number(Utilities.formatDate(date||new Date(),TZ_,'H'));return hour>=conf.quiet_start&&hour<conf.quiet_end;}
function frequencyBlocked_(ctx,customer,except){var cutoff=Date.now()-7*86400000;return ctx.table('MessageLog').filter(function(m){return m.customer_id===customer&&m.id!==except&&['sent','delivered','sending','unknown','manual_pending'].indexOf(m.status)!==-1&&Date.parse(m.last_attempt_at||m.sent_at||m.created_at)>cutoff;}).length>=config_(ctx).frequency_per_7days;}
function variables_(ctx,c,voucher){var o=entity_(ctx,'Outlets',c.workshop_id);return {name:c.name,code:voucher?voucher.code:'-',value:voucher?(voucher.type==='fixed'?'Rp'+voucher.value.toLocaleString('id-ID'):voucher.type==='percent'?voucher.value+'%':voucher.type==='free_check'?'cek servis gratis':'item gratis'):'-',expiry:voucher?voucher.expires_at.slice(0,10):'-',workshop:o.name,plate:c.plate,next_service_date:c.next_service_date,link:o.booking_url||'https://www.google.com/maps?q='+o.lat+','+o.lng};}
function renderMessage_(text,vars){return text.replace(/\{([a-z_]+)\}/g,function(all,key){assert_(Object.prototype.hasOwnProperty.call(vars,key),'VALIDATION','Variabel template tidak dikenal: '+key);return String(vars[key]);});}
function enqueueMessage_(ctx,customerId,template,meta){var c=entity_(ctx,'Customers',customerId);assert_(c.wa_opt_in&&!c.deleted,'OPTED_OUT','Pelanggan belum opt-in atau sudah berhenti.');var old=ctx.table('MessageLog').find(function(m){return m.dedupe_key===meta.dedupe_key;});if(old)return old;var conf=config_(ctx),v=meta.voucher_id?entity_(ctx,'Vouchers',meta.voucher_id):null,vars=variables_(ctx,c,v);var m=ctx.add('MessageLog',{customer_id:c.id,template:one_(template,['voucher_issued','service_reminder','win_back']),provider:conf.wa_provider,status:'queued',error:'',attempts:0,next_retry_at:now_(),provider_id:'',sent_at:'',delivered_at:'',last_attempt_at:'',cycle_id:meta.cycle_id||c.cycle_id,stage:meta.stage||'',voucher_id:meta.voucher_id||'',campaign_id:meta.campaign_id||'',campaign_cycle_id:meta.campaign_cycle_id||'',dedupe_key:meta.dedupe_key,variables:vars,manual_url:''},meta.dedupe_key);return m;}
function messagePublic_(m){return {id:m.id,status:m.status,provider:m.provider,attempts:m.attempts,error:m.error};}
function manualOpen_(ctx,p){var m=entity_(ctx,'MessageLog',id_(p.message_id)),c=entity_(ctx,'Customers',m.customer_id),conf=config_(ctx);if(m.campaign_id){var campaign=entity_(ctx,'Campaigns',m.campaign_id);assert_(campaign.status!=='paused'&&campaign.status!=='draft','CAMPAIGN_PAUSED','Campaign dijeda.');}assert_(m.provider==='wa_link','VALIDATION','Pesan tidak memakai tautan manual.');assert_(m.status==='queued'||m.status==='retry'||m.status==='manual_pending','CONFLICT','Pesan sudah dikirim/dibatalkan.');assert_(c.wa_opt_in&&!c.deleted,'OPTED_OUT','Pelanggan opt-out.');assert_(inQuietWindow_(conf),'QUIET_HOURS','Kirim hanya pukul 08.00–19.00 WIB.');assert_(!frequencyBlocked_(ctx,c.id,m.id),'FREQUENCY_CAP','Batas frekuensi pelanggan tercapai.');if(m.voucher_id){var v=entity_(ctx,'Vouchers',m.voucher_id);assert_(v.approval_status==='approved'&&Date.parse(v.expires_at)>Date.now()&&v.status!=='void'&&v.status!=='redeemed','VALIDATION','Voucher belum disetujui/tidak aktif.');}
  m.variables=variables_(ctx,c,m.voucher_id?entity_(ctx,'Vouchers',m.voucher_id):null);m.manual_url='https://wa.me/'+c.phone.slice(1)+'?text='+encodeURIComponent(renderMessage_(conf['template_'+m.template],m.variables));m.status='manual_pending';m.last_attempt_at=now_();ctx.put('MessageLog',m);audit_(ctx,'message.manual_open','MessageLog',m.id,{});return {id:m.id,url:m.manual_url,status:m.status};}
function manualMessageStatus_(ctx,p){var m=entity_(ctx,'MessageLog',id_(p.message_id)),c=entity_(ctx,'Customers',m.customer_id);assert_(m.provider==='wa_link'&&m.status==='manual_pending','VALIDATION','Konfirmasi hanya untuk tautan manual yang dibuka.');assert_(c.wa_opt_in&&!c.deleted,'OPTED_OUT','Pelanggan telah berhenti.');assert_(inQuietWindow_(config_(ctx)),'QUIET_HOURS','Konfirmasi kirim hanya dalam jam kirim.');assert_(p.sent===true,'VALIDATION','Konfirmasi pesan sudah dikirim dari WhatsApp.');m.status='sent';m.sent_at=now_();m.attempts=1;m.manual_url='';ctx.put('MessageLog',m);voucherMessageState_(ctx,m,'sent');audit_(ctx,'message.manual_sent','MessageLog',m.id,{self_reported:true});return {id:m.id,status:m.status,deliveryVerified:false};}
function listMessages_(ctx){return ctx.table('MessageLog').map(function(m){var copy=Object.assign({},m);delete copy.manual_url;delete copy.variables;return copy;});}
function voucherMessageState_(ctx,m,status){if(m.voucher_id){var v=entity_(ctx,'Vouchers',m.voucher_id);if(['issued','sent','delivered'].indexOf(v.status)!==-1){if(status==='delivered'||v.status==='issued')v.status=status;ctx.put('Vouchers',v);}}}
var WhatsAppProvider = {
  wa_link:function(c,m,conf){return {status:'manual_pending',id:'',url:'https://wa.me/'+c.phone.slice(1)+'?text='+encodeURIComponent(renderMessage_(conf['template_'+m.template],m.variables))};},
  fonnte:function(c,m,conf){var token=PropertiesService.getScriptProperties().getProperty('FONNTE_TOKEN');assert_(token,'PROVIDER_CONFIG','Isi FONNTE_TOKEN di Script Properties.');var resp=UrlFetchApp.fetch('https://api.fonnte.com/send',{method:'post',headers:{Authorization:token},payload:{target:c.phone.slice(1),message:renderMessage_(conf['template_'+m.template],m.variables),countryCode:'62',preview:'false'},muteHttpExceptions:true});return parseProviderResponse_(resp,'fonnte');},
  meta_cloud:function(c,m,conf){var props=PropertiesService.getScriptProperties(),token=props.getProperty('META_ACCESS_TOKEN'),number=props.getProperty('META_PHONE_NUMBER_ID');assert_(token&&/^\d+$/.test(number||''),'PROVIDER_CONFIG','Isi META_ACCESS_TOKEN dan META_PHONE_NUMBER_ID.');assert_(/^v\d+\.\d+$/.test(conf.meta_graph_version),'PROVIDER_CONFIG','Versi Graph API tidak valid.');var body={messaging_product:'whatsapp',to:c.phone.slice(1),type:'template',template:{name:conf['meta_template_'+m.template],language:{code:conf.meta_language},components:[{type:'body',parameters:conf.meta_variable_order.map(function(key){return {type:'text',text:String(m.variables[key]||'-')};})}]}};var resp=UrlFetchApp.fetch('https://graph.facebook.com/'+conf.meta_graph_version+'/'+number+'/messages',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+token},payload:JSON.stringify(body),muteHttpExceptions:true});return parseProviderResponse_(resp,'meta_cloud');}
};
function parseProviderResponse_(response,provider){var status=response.getResponseCode(),json;try{json=JSON.parse(response.getContentText());}catch(e){return {status:'unknown',error:'Non-JSON provider response'};}if(status>=500)return {status:'unknown',error:'Provider HTTP '+status+'; confirm before retry.'};if(status<200||status>=300)return {status:'failed',error:'Provider HTTP '+status};if(provider==='fonnte'){if(json.status===true)return {status:'sent',id:Array.isArray(json.id)?json.id.join(','):String(json.id||'')};return {status:'failed',error:str_(String(json.reason||json.detail||'Provider rejected request'),300)};}if(json.messages&&json.messages[0])return {status:'sent',id:json.messages[0].id};return {status:'failed',error:'Meta rejected request'};}
function processMessage_(messageId){var system={id:'system',role:'admin'},m=readTable_('MessageLog',false).find(function(r){return r.id===messageId;});if(!m||['queued','retry'].indexOf(m.status)===-1||Date.parse(m.next_retry_at)>Date.now())return;var claimId='message-claim-'+m.id+'-'+m.attempts+'-'+digest_(m.next_retry_at).slice(0,10);
  var claim=transaction_(system,{action:'internal.message.claim',requestId:claimId,payload:{id:m.id}},function(ctx){var row=entity_(ctx,'MessageLog',m.id),c=ctx.table('Customers').find(function(c){return c.id===row.customer_id;}),conf=config_(ctx);if(!c||!c.wa_opt_in||c.deleted){row.status='cancelled';row.error='Customer opted out';ctx.put('MessageLog',row);return {skip:true};}if(row.stage&&row.cycle_id!==c.cycle_id){row.status='cancelled';row.error='Service cycle reset';ctx.put('MessageLog',row);return {skip:true};}if(row.campaign_id){var campaign=entity_(ctx,'Campaigns',row.campaign_id);if(campaign.status==='paused'||campaign.status==='draft')return {skip:true,deferred:true};if(row.campaign_cycle_id&&row.campaign_cycle_id!==campaign.cycle_key){row.status='cancelled';row.error='Campaign replaced';ctx.put('MessageLog',row);return {skip:true};}}if(!inQuietWindow_(conf)||frequencyBlocked_(ctx,c.id,row.id))return {skip:true,deferred:true};if(row.voucher_id){var v=entity_(ctx,'Vouchers',row.voucher_id);if(v.approval_status==='pending')return {skip:true,deferred:true};if(v.approval_status!=='approved'||['void','redeemed','expired'].indexOf(v.status)!==-1||Date.parse(v.expires_at)<Date.now()){row.status='cancelled';row.error='Voucher unavailable';ctx.put('MessageLog',row);return {skip:true};}}
    row.variables=variables_(ctx,c,row.voucher_id?entity_(ctx,'Vouchers',row.voucher_id):null);row.last_attempt_at=now_();if(row.provider==='wa_link'){row.status='manual_pending';ctx.put('MessageLog',row);return {skip:true,manual:true};}row.status='sending';row.attempts++;ctx.put('MessageLog',row);return {message:row,customer:c,config:conf};});
  // Deferred claims must be retried with a new key because request IDs are durable.
  if(claim.deferred){transaction_(system,{action:'internal.defer',requestId:'defer-'+uuid_(),payload:{id:m.id}},function(ctx){var row=entity_(ctx,'MessageLog',m.id);row.next_retry_at=new Date(Date.now()+15*60000).toISOString();ctx.put('MessageLog',row);return {};});return;}
  if(claim.skip)return;var result,dispatchLock=LockService.getScriptLock();try{assert_(dispatchLock.tryLock(15000),'BUSY','Send gate busy');var freshCustomer=readTable_('Customers',false).find(function(c){return c.id===claim.customer.id;}),freshMessage=readTable_('MessageLog',false).find(function(m){return m.id===claim.message.id;});if(!freshCustomer||!freshCustomer.wa_opt_in||freshCustomer.deleted||freshMessage.status==='cancelled'){result={status:'cancelled',error:'Customer opted out before provider call'};}else if(!inQuietWindow_(config_())){result={status:'failed',error:'Quiet hours began before provider call'};}else result=WhatsAppProvider[claim.message.provider](freshCustomer,claim.message,claim.config);}catch(e){result={status:e.code==='PROVIDER_CONFIG'?'failed':'unknown',error:e.code==='PROVIDER_CONFIG'?e.message:'Ambiguous provider timeout; verify delivery before resending.'};}finally{dispatchLock.releaseLock();}
  return transaction_(system,{action:'internal.message.result',requestId:'message-result-'+claim.message.id+'-'+claim.message.attempts,payload:result},function(ctx){var row=entity_(ctx,'MessageLog',claim.message.id);if(row.status==='delivered'||row.status==='cancelled')return {id:row.id,status:row.status};row.status=result.status;row.error=result.error||'';row.provider_id=result.id||row.provider_id;if(result.status==='sent'){row.sent_at=now_();voucherMessageState_(ctx,row,'sent');}if(result.status==='failed'&&row.attempts<3){row.status='retry';row.next_retry_at=new Date(Date.now()+Math.pow(2,row.attempts-1)*5*60000).toISOString();}ctx.put('MessageLog',row);return messagePublic_(row);});
}
function webhook_(e){var provider=one_(e.parameter.webhook,['fonnte']),secret=PropertiesService.getScriptProperties().getProperty('WEBHOOK_SECRET');assert_(secret&&equal_(e.parameter.secret||'',secret),'FORBIDDEN','Webhook tidak terverifikasi.');var body={};if(e.postData&&e.postData.contents){try{body=JSON.parse(e.postData.contents);}catch(err){body=e.parameter;}}else body=e.parameter;
  var sender=body.sender||body.from||'',text=String(body.message||body.text||'').trim(),eventId=String(body.event_id||body.id||digest_(JSON.stringify(body))),request={action:'internal.webhook',requestId:'webhook-'+digest_(provider+'|'+eventId+'|'+(body.state||body.status||text)),payload:{hash:digest_(JSON.stringify(body))}};
  return transaction_({id:'webhook',role:'admin'},request,function(ctx){ctx.add('WebhookEvents',{provider:provider,event_id:str_(eventId,300,true),payload_hash:request.payload.hash,status:'processed'},request.requestId);if(text.toUpperCase()==='STOP'&&sender){var normalized=phone_(String(sender));ctx.table('Customers').filter(function(c){return c.phone===normalized&&!c.deleted;}).forEach(function(c){consent_(ctx,c,false,'workshop','Inbound STOP via authenticated Fonnte webhook');ctx.put('Customers',c);cancelPendingMessages_(ctx,c.id);});}
    var providerId=String(body.id||body.message_id||''),state=String(body.state||body.status||'').toLowerCase(),states={delivered:'delivered',read:'delivered',sent:'sent',failed:'failed',2:'delivered',3:'delivered'};var next=states[state];if(providerId&&next){ctx.table('MessageLog').filter(function(m){return m.provider==='fonnte'&&m.provider_id.split(',').indexOf(providerId)!==-1;}).forEach(function(m){if(m.status==='delivered'&&next!=='delivered')return;if(['cancelled','unknown'].indexOf(m.status)!==-1&&next!=='delivered')return;m.status=next;if(next==='delivered')m.delivered_at=now_();if(next==='sent'&&!m.sent_at)m.sent_at=now_();if(next==='failed')m.error='Provider delivery failure';ctx.put('MessageLog',m);if(next==='sent'||next==='delivered')voucherMessageState_(ctx,m,next);});}return {received:true};});}
