const fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
function harness(){let clock=Date.parse('2026-10-12T02:00:00Z'),counter=0,locked=false,failTable=null;const properties=new Map(),cache=new Map(),files=new Map(),folders=new Map(),sheets=new Map();
 class FakeDate extends Date{constructor(...args){super(...(args.length?args:[clock]));}static now(){return clock;}}
 function formatDate(d,tz,format){const date=new Date(d),parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(date).map(p=>[p.type,p.value]));return format==='H'?String(Number(parts.hour)):`${parts.year}-${parts.month}-${parts.day}`;}
 class Range{constructor(sheet,row,col,nr,nc){Object.assign(this,{sheet,row,col,nr,nc});}getValues(){return Array.from({length:this.nr},(_,i)=>Array.from({length:this.nc},(_,j)=>this.sheet.values[this.row-1+i]?.[this.col-1+j]??''));}setValues(rows){if(failTable===this.sheet.name){failTable=null;throw new Error('Injected interruption');}rows.forEach((r,i)=>{this.sheet.values[this.row-1+i]??=[];r.forEach((v,j)=>this.sheet.values[this.row-1+i][this.col-1+j]=v);});return this;}clearContent(){for(let i=0;i<this.nr;i++)for(let j=0;j<this.nc;j++)if(this.sheet.values[this.row-1+i])this.sheet.values[this.row-1+i][this.col-1+j]='';return this;}setBackground(){return this;}setFontColor(){return this;}setFontWeight(){return this;}setWrapStrategy(){return this;}setDataValidation(){return this;}setWrap(){return this;}}
 class Sheet{constructor(name){this.name=name;this.values=[];this.maxRows=1000;this.maxColumns=26;}getDataRange(){return new Range(this,1,1,Math.max(1,this.getLastRow()),Math.max(1,this.values[0]?.length||1));}getRange(row,col,nr=1,nc=1){return new Range(this,row,col,nr,nc);}getLastRow(){for(let i=this.values.length-1;i>=0;i--)if(this.values[i]?.some(v=>v!==''))return i+1;return 0;}getMaxRows(){return this.maxRows;}getMaxColumns(){return this.maxColumns;}insertRowsAfter(_,n){this.maxRows+=n;}insertColumnsAfter(_,n){this.maxColumns+=n;}setFrozenRows(){}getProtections(){return [true];}clearContents(){this.values=[];}setColumnWidths(){}protect(){return{getEditors:()=>[],removeEditors(){},canDomainEdit:()=>false};}}
 const ss={getId:()=> 'spreadsheet-demo',getSheetByName:name=>sheets.get(name),insertSheet:name=>{const s=new Sheet(name);sheets.set(name,s);return s;},setSpreadsheetTimeZone(){}};
 function blob(input,mime,name){const b=typeof input==='string'?Buffer.from(input):Buffer.from(input.map(v=>(v+256)%256));return{getBytes:()=>[...b],getDataAsString:()=>b.toString(),getContentType:()=>mime||'text/plain',getName:()=>name};}
 function folder(name){const id='folder-'+(++counter),obj={id,name,children:[],fileIds:[],getId:()=>id,getFoldersByName(n){return iterator(this.children.filter(f=>f.name===n));},createFolder(n){const f=folder(n);this.children.push(f);return f;},getFilesByName(n){return iterator(this.fileIds.map(i=>files.get(i)).filter(f=>f.name===n&&!f.trashed));},createFile(a,b,c){const id='file-'+(++counter),data=typeof a==='string'?blob(b,c,a):a,f={id,name:typeof a==='string'?a:a.getName(),data,trashed:false,getId:()=>id,getUrl:()=> 'https://drive.google.com/file/d/'+id+'/view',getBlob:()=>data,setTrashed(value){this.trashed=value;}};files.set(id,f);this.fileIds.push(id);return f;}};folders.set(id,obj);return obj;}
 function iterator(arr){let i=0;return{hasNext:()=>i<arr.length,next:()=>arr[i++]};}
 const sandbox={Date:FakeDate,console:{error(){}},Buffer,
  PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)||null,setProperty(k,v){properties.set(k,String(v));return this;},deleteProperty:k=>properties.delete(k)})},
  CacheService:{getScriptCache:()=>({get:k=>cache.get(k)||null,put:(k,v)=>cache.set(k,v),remove:k=>cache.delete(k)})},
  Utilities:{getUuid:()=>crypto.randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,s)=>[...crypto.createHash('sha256').update(s).digest()],formatDate,base64Decode:s=>[...Buffer.from(s,'base64')],base64Encode:b=>Buffer.from(b).toString('base64'),newBlob:blob},
  LockService:{getScriptLock:()=>({tryLock(){if(locked)return false;locked=true;return true;},waitLock(){if(locked)throw new Error('Nested lock');locked=true;},releaseLock(){locked=false;}})},
  SpreadsheetApp:{openById:()=>ss,getActiveSpreadsheet:()=>ss,create:()=>ss,flush(){},WrapStrategy:{CLIP:'clip'},ProtectionType:{SHEET:'sheet'},newDataValidation:()=>({requireValueInList(){return this;},setAllowInvalid(){return this;},build(){return{};}})},
  DriveApp:{createFolder:folder,getFolderById:id=>folders.get(id),getFileById:id=>{if(!files.has(id))throw new Error('Missing file');return files.get(id);}},MimeType:{PLAIN_TEXT:'text/plain',CSV:'text/csv'},
  ContentService:{MimeType:{JSON:'application/json'},createTextOutput:text=>({text,setMimeType(){return this;}})},
  ScriptApp:{getProjectTriggers:()=>[],deleteTrigger(){},newTrigger:()=>({timeBased(){return this;},atHour(){return this;},nearMinute(){return this;},everyDays(){return this;},inTimezone(){return this;},everyMinutes(){return this;},create(){return{};}})},
  UrlFetchApp:{fetch:()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({status:true,id:['provider-1']})})}
 };
 const ctx=vm.createContext(sandbox);vm.runInContext(fs.readdirSync('backend').filter(f=>f.endsWith('.gs')).map(f=>fs.readFileSync('backend/'+f,'utf8')).join('\n'),ctx,{filename:'backend-bundle.gs'});
 properties.set('ADMIN_PIN','12345678');properties.set('DEMO_PIN','23456789');properties.set('DEMO_MODE','true');ctx.setup();ctx.createAdminAccount();ctx.seedDemoData();
 function api(action,payload={},token='',requestId=crypto.randomUUID()){return JSON.parse(ctx.doPost({postData:{contents:JSON.stringify({action,payload,token,requestId,clientId:'client-demo'})},parameter:{}}).text);}
 function login(username,pin='23456789'){const r=api('auth.login',{username,pin});if(!r.ok)throw new Error(JSON.stringify(r.error));return r.data;}
 function rows(name){return JSON.parse(JSON.stringify(ctx.readTable_(name,false)));}
 return{ctx,api,login,rows,properties,files,ss,sandbox,setTime:v=>{clock=Date.parse(v);},interruptAt:t=>{failTable=t;},add(table,row){const lock=sandbox.LockService.getScriptLock();lock.waitLock();try{const c=ctx.makeContext_({id:'test-admin',role:'admin'},crypto.randomUUID());c.add(table,row,row.id||crypto.randomUUID());ctx.applyOps_(c.ops());}finally{lock.releaseLock();}},json:v=>JSON.parse(JSON.stringify(v))};
}
module.exports={harness};
