import './style.css';
import {t,lang,setLanguage} from './i18n.js';
import {esc,icon,toast,today,empty} from './ui.js';
import {session,saveSession,logoutLocal,queueRows,getMeta,setMeta} from './store.js';
import {read,request} from './api.js';
import {IS_CONFIGURED,VERSION} from './config.js';
import {initSync,syncNow} from './sync.js';
import {demoData,demoUser} from './demo.js';
import {todayPage,reportsPage,leadPage,trainingPage,syncPage,schedulePage,adminPage,reviewPage} from './pages.js';
import {fieldPage} from './field.js';
import {loyaltyPage} from './loyalty.js';
export const state={session:null,bootstrap:null,page:'today',demo:new URLSearchParams(location.search).get('demo')==='1',syncing:false,offline:false};
let generation=0,installEvent;
export const manager=()=>['admin','supervisor'].includes(state.session?.user.role);
export async function load(action,payload={},opts={}){if(state.demo)return demoData(action,payload);const result=await read(action,payload,opts);if(result.offline){state.offline=true;toast(t('offline'));}return result.data;}
export async function mutate(action,payload){if(state.demo)throw new Error('Demo hanya-baca. Hubungkan GAS untuk menyimpan data.');const data=await request(action,payload);toast(t('save')+' ✓');return data;}
export const app={state,load,mutate,manager,navigate:page=>{location.hash=page;},refresh:()=>render(),reloadBootstrap:async()=>{state.bootstrap=await load('me.bootstrap');}};
function allowedPages(){const role=state.session.user.role;return role==='client_viewer'?['reports','leads','loyalty']:role==='admin'?['today','reports','leads','loyalty','review','schedule','training','admin','sync']:role==='supervisor'?['today','reports','leads','loyalty','review','schedule','training','sync']:['today','reports','leads','loyalty','training','sync'];}
function nav(p){return `<a class="nav-link ${state.page===p?'active':''}" href="#${p}" ${state.page===p?'aria-current="page"':''}>${icon(p)}<span>${t(p)}</span></a>`;}
function shell(){const user=state.session.user,pages=allowedPages(),mobile=pages.filter(p=>['today','reports','leads','loyalty','sync'].includes(p)).slice(0,5);document.querySelector('#app').innerHTML=`${state.demo?'<div class="demo-banner">PRATINJAU DEMO · Seluruh angka simulasi · Penyimpanan dinonaktifkan</div>':''}<div class="app-layout"><aside class="sidebar" aria-label="Navigasi utama"><div class="brand"><div class="trw-logo">TRW</div><div class="brand-title">Route to<br>Preference</div></div><div class="eyebrow">WORKSPACE</div><nav>${pages.map(nav).join('')}</nav><div class="sidebar-footer"><img class="araia-logo" src="./assets/araia.png" width="800" height="320" alt="ARAIA Group"><div class="pilot-label">${t('pilot')} · 4 MONTHS</div><button class="btn ghost" data-global="logout" style="color:#d9dbe1;margin-top:12px">${icon('logout')}${t('logout')}</button></div></aside><div class="shell"><header class="topbar"><div class="stack"><button class="btn secondary icon-only mobile-menu" data-global="menu" aria-label="Navigasi">${icon('menu')}</button><button class="btn ghost icon-only desktop-collapse" data-global="collapse" aria-label="Collapse sidebar">${icon('menu')}</button><div class="breadcrumb">Workspace &nbsp;/&nbsp; <b>${t(state.page==='field'?'today':state.page)}</b></div></div><div class="topbar-right"><button class="sync-chip ${!navigator.onLine?'offline':''}" id="sync-chip" data-global="sync">${navigator.onLine?t('online'):t('offline')}</button><button class="btn ghost lang-btn" data-global="lang" aria-label="ID / EN EN / ID">${lang().toUpperCase()} / ${lang()==='id'?'EN':'ID'}</button><button class="btn ghost icon-only" data-global="theme" aria-label="${document.documentElement.classList.contains('dark')?t('light'):t('dark')}">${icon('sun')}</button><div class="avatar user-avatar">${esc(user.name.slice(0,2).toUpperCase())}</div><div class="user-block"><div class="user-name">${esc(user.name)}</div><div class="user-role">${esc(user.role.toUpperCase())} · ${esc(user.area)}</div></div></div></header><main id="main" class="content" tabindex="-1"><div class="grid four"><div class="skeleton large"></div><div class="skeleton large"></div><div class="skeleton large"></div><div class="skeleton large"></div></div><div class="skeleton medium"></div><div class="skeleton large"></div></main></div></div><nav class="bottom-nav" aria-label="Navigasi mobile">${mobile.map(p=>`<a href="#${p}" class="${state.page===p?'active':''}" ${state.page===p?'aria-current="page"':''}>${icon(p)}<span>${t(p)}</span></a>`).join('')}</nav>`;}
export async function render(){const gen=++generation;if(!state.session)return login();state.page=(location.hash.slice(1).split('?')[0]|| (state.session.user.role==='client_viewer'?'reports':'today'));if(!allowedPages().includes(state.page)&&state.page!=='field'){state.page='today';if(state.session.user.role==='client_viewer')state.page='reports';}shell();document.body.classList.remove('menu-open');try{
  if(!state.bootstrap)state.bootstrap=await load('me.bootstrap');if(gen!==generation)return;
  const root=document.querySelector('#main');if(!state.demo&&Date.parse(state.session.expiresAt)<=Date.now())root.insertAdjacentHTML('afterbegin',`<div class="notice">${t('relogin')} <button class="btn small secondary" data-global="reauth">${t('login')}</button></div>`);
  const page=document.createElement('div');root.append(page);root.querySelectorAll('.skeleton,.grid').forEach(el=>el.remove());const handlers={today:todayPage,reports:reportsPage,leads:leadPage,training:trainingPage,sync:syncPage,schedule:schedulePage,admin:adminPage,review:reviewPage,loyalty:loyaltyPage,field:fieldPage};await handlers[state.page](page,app);if(gen!==generation)return;updateSyncChip();
}catch(e){if(gen!==generation)return;if(e.code==='AUTH_EXPIRED'){toast(t('relogin'),true);login(true);}else{document.querySelector('#main').innerHTML=`<div class="card">${empty(e.message)}<button class="btn primary" data-global="refresh">${t('refresh')}</button></div>`;}}}
function login(reauth=false){const prior=state.session?.user;document.querySelector('#app').innerHTML=`<main id="main" class="login-layout"><section class="login-story"><div class="brand"><div class="trw-logo">TRW</div><div class="brand-title">Route to Preference<br><small>ARAIA GROUP</small></div></div><div><div class="eyebrow" style="color:#b4bbc7">JABODETABEK · FIELD PILOT</div><h1>Setiap kunjungan,<br><span>membangun<br>kepercayaan.</span></h1><p>Eksekusi yang konsisten. Insight yang dapat dipakai. Alasan untuk kembali ke bengkel.</p></div><div class="story-footer"><div><strong>16</strong><small>MINGGU PILOT</small></div><div><strong>2.400</strong><small>TARGET KUNJUNGAN FM</small></div><div><strong>80</strong><small>WORKSHOP SPG UNIK</small></div></div></section><section class="login-panel"><img class="araia-logo" src="./assets/araia.png" width="800" height="320" alt="ARAIA Group"><div class="stack split"><span class="eyebrow">TRW ROUTE TO PREFERENCE</span><button class="btn ghost" data-global="lang">${lang().toUpperCase()} / ${lang()==='id'?'EN':'ID'}</button></div><h2>${reauth?t('relogin'):t('login')+' ke workspace'}</h2><p class="muted">Gunakan akun yang diberikan supervisor Anda.</p>${!IS_CONFIGURED?'<div class="notice">Backend belum dikonfigurasi. Panduan tersedia di docs/SETUP.md. Anda bisa melihat demo UI di bawah.</div>':''}<form id="login-form"><label class="field"><span>Username</span><input name="username" autocomplete="username" autocapitalize="none" required maxlength="60" value="${esc(prior?.username||'')}"></label><label class="field"><span>PIN</span><input name="pin" type="password" inputmode="numeric" pattern="[0-9]{8,12}" minlength="8" maxlength="12" autocomplete="current-password" required aria-describedby="pin-help"></label><p class="field-help" id="pin-help">8–12 digit · Sesi berlaku 12 jam</p><button class="btn primary" type="submit">${t('login')}${icon('arrow')}</button></form><p class="login-foot">Data lapangan yang belum tersinkron tetap tersimpan pada perangkat ini. Login awal membutuhkan internet.</p><div class="stack"><a class="btn secondary" href="?demo=1#today">Pratinjau demo</a><button class="btn ghost" data-global="install">${t('install')}</button></div><p class="login-foot">${t('installIos')}</p><small>v${VERSION} · Asia/Jakarta</small></section></main>`;
  document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button'),data=new FormData(e.target);btn.disabled=true;try{const s=await request('auth.login',{username:String(data.get('username')).toLowerCase(),pin:String(data.get('pin'))});if(prior&&prior.id!==s.user.id)toast('Antrean akun sebelumnya tetap tersimpan terpisah.');await saveSession(s);e.target.reset();state.session=s;state.bootstrap=null;state.demo=false;await render();syncNow();}catch(err){toast(err.message,true);}finally{if(btn.isConnected)btn.disabled=false;}};}
async function updateSyncChip(){const el=document.querySelector('#sync-chip');if(!el||!state.session)return;const rows=state.demo?[]:await queueRows(state.session.user.id),pending=rows.filter(r=>r.status!=='done').length;el.textContent=state.syncing?'Sync…':!navigator.onLine?t('offline'):pending?`${pending} ${t('queued')}`:t('online');el.classList.toggle('offline',!navigator.onLine||pending>0);}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-global]');if(!b)return;const action=b.dataset.global;try{if(action==='theme'){document.documentElement.classList.toggle('dark');localStorage.setItem('trw-theme',document.documentElement.classList.contains('dark')?'dark':'light');}if(action==='lang'){setLanguage(lang()==='id'?'en':'id');await render();}if(action==='menu')document.body.classList.toggle('menu-open');if(action==='collapse')document.body.classList.toggle('collapsed');if(action==='refresh')await render();if(action==='sync'){if(!state.demo)syncNow();else app.navigate('sync');}if(action==='reauth')login(true);if(action==='install'){if(installEvent){await installEvent.prompt();installEvent=null;}else toast(t('installIos'));}if(action==='logout'){if(!state.demo){const pending=(await queueRows(state.session.user.id)).filter(r=>r.status!=='done').length;if(pending)toast(`${pending} antrean tetap disimpan untuk akun ini.`);if(navigator.onLine)try{await request('auth.logout',{});}catch{}await logoutLocal(state.session.user.id);}state.session=null;state.bootstrap=null;state.demo=false;history.replaceState(null,'',location.pathname);login();}}
catch(err){toast(err.message,true);}});
window.addEventListener('hashchange',()=>{if(!location.hash.startsWith('#field')&&document.querySelector('[data-field-draft]'))window.dispatchEvent(new Event('trw-save-draft'));render();});
window.addEventListener('trw-sync',e=>{state.syncing=!!e.detail.running;updateSyncChip();if(e.detail.authExpired)toast(t('relogin'),true);});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});
if('serviceWorker'in navigator&&!import.meta.env.DEV){navigator.serviceWorker.register('./sw.js').catch(()=>{});const hadController=!!navigator.serviceWorker.controller;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(hadController)toast('Aplikasi diperbarui. Muat ulang saat form sudah disimpan.');});}
// register URL must be relative to deployment root, not the hashed asset directory.
if(localStorage.getItem('trw-theme')==='dark')document.documentElement.classList.add('dark');setLanguage(lang());
state.session=state.demo?{user:demoUser,expiresAt:new Date(Date.now()+43200000).toISOString(),token:''}:await session();initSync();await render();if(!state.demo&&state.session)syncNow();
