import {today} from './ui.js';
const id=i=>'demo-outlet-'+i;
export const demoUser={id:'demo-fm1',username:'fm1',name:'FM Demo · Jakarta',role:'fm',area:'Jakarta'};
const names=['Bengkel Prima Motor','Garasi Sahabat Auto','Bengkel Sinar Jaya','Prima Teknik Otomotif','Sentra Mobil Jakarta','Bengkel Maju Bersama','Garasi Aman Motor'];
const outlets=names.map((name,i)=>({id:id(i),name,area:'Jakarta Selatan',address:['Jl. Radio Dalam Raya','Jl. Panglima Polim','Jl. Fatmawati Raya','Jl. Cipete Raya','Jl. Antasari','Jl. Kemang Raya','Jl. Tendean'][i],lat:-6.25+i*.004,lng:106.793+i*.003,booking_url:'https://www.google.com/maps?q='+(-6.25+i*.004)+','+(106.793+i*.003),active:true}));
const tasks=outlets.map((outlet,i)=>({id:'demo-roster-'+i,user_id:demoUser.id,outlet_id:outlet.id,outlet,date:today(),position:i+1,backup:i===6,status:i<2?'completed':'planned',visit_status:i<2?'approved':i===2?'pending':'',visit_id:i<3?'demo-visit-'+i:''}));
const visits=tasks.slice(0,3).map((a,i)=>({id:a.visit_id,user_id:demoUser.id,outlet_id:a.outlet.id,assignment_id:a.id,kind:'fm',date:today(),status:a.visit_status,gps_flags:i===2?['accuracy_over_100m']:[],stock:[{sku:'TRW brake pad',qty:10}],permission:true,posm:true,planogram:true,next_action:'Follow-up ketersediaan produk',retailer_questions:'Retailer tertarik',distance_m:42,accuracy:25}));
export function demoData(action,p={}){if(action==='me.bootstrap')return {user:demoUser,date:today(),readiness:true,outlets,config:{option_spg:true,option_fm:true,fm_target:2400,fm_threshold:2280,survey_target:800,wa_provider:'wa_link',consent_text:'Saya setuju menerima voucher dan pengingat servis melalui WhatsApp. Balas STOP untuk berhenti.',consent_text_version:'wa-opt-in-v1'},training:demoData('training.list')};
 if(action==='me.today')return {date:today(),tasks,visits,exceptions:[],planned:6,completed:2};
 if(action==='report.kpi')return {scope:'pilot',options:{fm:true,spg:true},spg:{filledShifts:24,plannedShifts:80,uniqueWorkshops:24,workshopTarget:80,validSurveys:237,surveyTarget:800,workshopWeeksMeeting10:20},fm:{acceptedVisits:684,target:2400,threshold:2280,pilotTarget:2400,pilotThreshold:2280,coveragePct:28.5,uniqueOutlets:146,meets95:false},quality:{submitted:720,accepted:708,pending:9,rejected:3,gpsFlags:6,backChecks:36,clientApprovedExceptions:8},learning:{recordedLeads:47,qualifiedOpportunities:28,acknowledged:24,verifiedSales:8,verifiedSalesValue:12600000,overdueHandOff:2},loyalty:{sent:96,delivered:81,failed:4,manualPending:7,issued:120,redeemed:31,redemptionRate:25.83,returnVisitRate:18.75,voucherCost:1450000,redeemedDiscountValue:1450000,redeemedTransactionValue:11200000,workshops:[]},trend:Array.from({length:10},(_,i)=>({date:'2026-10-'+(i+12),submitted:30,accepted:[27,29,30,28,30,29,30,28,29,30][i]})),decisionDrivers:{safety:74,quality:68,price:42,mechanic_recommendation:35,availability:18}};
 if(action==='lead.list')return [{id:'demo-lead1',outlet_id:id(0),outlet_name:names[0],category:'Brake pad',need:'Butuh alternatif brake pad untuk pelanggan harian.',status:'handed_off',qualified:true,overdue:false,age_days:1,next_action:'Konfirmasi stok & harga',created_at:new Date().toISOString()},{id:'demo-lead2',outlet_id:id(2),outlet_name:names[2],category:'Shock absorber',need:'Permintaan shock absorber kendaraan keluarga.',status:'validated',qualified:true,overdue:true,age_days:3,next_action:'Follow-up recipient',created_at:new Date().toISOString()}];
 if(action==='customer.list')return [{id:'demo-customer1',label:'Pelanggan •••0123',workshop_id:id(0),wa_opt_in:true,next_service_date:'2027-04-12',points:120,tier:'Silver'}];
 if(action==='voucher.templates')return [{id:'demo-template1',name:'Cek Keselamatan Gratis',type:'free_check',value:0},{id:'demo-template2',name:'Voucher Rp50.000',type:'fixed',value:50000},{id:'demo-template3',name:'Diskon 10%',type:'percent',value:10}];
 if(action==='voucher.list')return [{id:'demo-voucher1',customer_id:'demo-customer1',template_id:'demo-template2',code:'TRW-ABCD-EFGH',type:'fixed',value:50000,status:'issued',approval_status:'pending',expires_at:'2026-11-08T23:59:59+07:00'}];
 if(action==='training.list')return {courses:[{id:'demo-training1',name:'DEMO · kesiapan lapangan (bukan materi produk)',questions:[{question:'Kapan merchandising dilakukan?',options:['Sebelum engage','Sesudah close']},{question:'Apakah opt-in WA diperlukan?',options:['Ya','Tidak']},{question:'Foto evidence harus?',options:['Sebelum/sesudah','Sesudah saja']},{question:'Survey harus?',options:['Sukarela','Dipaksa']},{question:'Sales outcome dikonfirmasi?',options:['Client','Diasumsikan staf']}]}],results:[{id:'demo-quiz1',user_id:demoUser.id,score:100,pass:true,practical_pass:true}]};
 if(action==='admin.list')return {rows:p.table==='Visits'?visits:p.table==='Outlets'?outlets:p.table==='Roster'?tasks:[]};
 if(['message.list','campaign.list'].includes(action))return [];
 throw new Error('Pratinjau demo hanya-baca. Hubungkan Apps Script untuk fungsi ini.');
}
