import {t} from './i18n.js';
import {esc,icon,field,area,select,check,options,values,dialog,formFooter,badge,toast,today} from './ui.js';
import {drafts,saveDraft,enqueueBatch} from './store.js';
import {compressPhoto,location,distance} from './media.js';
import {scheduleSync} from './sync.js';
import {heading} from './pages.js';
const reasons=[{value:'outlet_closed',label:'Outlet tutup'},{value:'no_permission',label:'Tidak diizinkan'},{value:'no_stock',label:'Tidak ada stok'},{value:'other',label:'Lainnya'}];
const drivers=[{value:'safety',label:'Keselamatan'},{value:'quality',label:'Kualitas'},{value:'price',label:'Harga'},{value:'mechanic_recommendation',label:'Rekomendasi mekanik'},{value:'availability',label:'Ketersediaan'},{value:'brand',label:'Merek'},{value:'other',label:'Lainnya'}];
const surveyFields=()=>field('Kode responden anonim yang konsisten (tanpa nama/nomor HP)','respondent_ref','text','','required maxlength="100" placeholder="W01-R01"')+check(t('eligible'),'eligible',false,'required')+check(t('consentSurvey'),'consent',false,'required')+select('Faktor keputusan utama','decision_driver',drivers)+field('Preferensi merek','brand_preference','text','','required maxlength="100"')+select('Keyakinan terhadap TRW (1–5)','confidence',['1','2','3','4','5'],'3')+area('Kebutuhan / alasan keputusan','need','','required maxlength="500"');
function photoInput(kind,photo){return `<label class="camera">${photo?`<img src="${photo.preview||'data:image/jpeg;base64,'+photo.base64}" alt="${esc(kind)} evidence"><small>${Math.round(photo.bytes/1024)} KB · JPEG</small>`:`${icon('camera')}<b>${t(kind==='before'?'before':kind==='after'?'after':'exception')}</b><small>JPEG · max 1280px · 1 MB</small>`}<input type="file" accept="image/*" capture="environment" data-camera="${esc(kind)}" aria-label="${t('capture')} ${esc(kind)}"></label>`;}
export async function fieldPage(root,app){const owner=app.state.session.user.id;let assignment;try{assignment=JSON.parse(sessionStorage.getItem('trw-assignment')||'null');}catch{}if(!assignment){root.innerHTML=heading(t('today'),'Pilih kunjungan dari Hari ini.')+`<a class="btn primary" href="#today">${t('back')}</a>`;return;}const all=await drafts(owner),stored=all.find(d=>d.assignment?.id===assignment.id&&!d.queued),draft=stored||{id:crypto.randomUUID(),owner,assignment,kind:app.state.session.user.role,step:0,startedAt:new Date().toISOString(),date:today(),gps:null,photos:{},fields:{permission:false,posm:false,planogram:false,stock_sku:'TRW',stock_qty:'0',interest:'none',next_action:''}};let step=draft.step||0,exception=!!draft.fields.exception;
 const save=async()=>{const form=root.querySelector('#visit-form');if(form)draft.fields={...draft.fields,...values(form)};draft.step=step;draft.fields.exception=exception;await saveDraft(draft);};
 const saveOnLeave=()=>save();window.addEventListener('trw-save-draft',saveOnLeave,{once:true});
 const render=()=>{const spg=draft.kind==='spg',labels=spg?['PREPARE','LISTEN','EXPLAIN','CAPTURE']:['VERIFY','EXECUTE','ENGAGE','CLOSE'],f=draft.fields;let body='';if(step===0)body=`<h2>${spg?'Siapkan TRW Confidence Conversation':'Verifikasi outlet & izin kerja'}</h2><div class="note-box">${esc(assignment.outlet.name)}<br>${esc(assignment.outlet.address)}</div><button type="button" class="btn secondary" style="margin-top:18px" data-gps>${icon('pin')}${t('gps')}</button>${draft.gps?`<div class="gps-result"><div class="split"><b>${draft.gps.lat.toFixed(5)}, ${draft.gps.lng.toFixed(5)}</b>${badge(Math.round(draft.gps.accuracy)+' m',draft.gps.accuracy>100?'warn':'good')}</div><p style="margin:10px 0 0">Jarak ke outlet ${Math.round(distance(draft.gps,assignment.outlet))} m · ${draft.gps.accuracy>100||distance(draft.gps,assignment.outlet)>200?'Ditandai untuk supervisor':'GPS sesuai'}</p></div>`:''}${check(t('permission'),'permission',f.permission)}<button type="button" class="btn ghost" data-exception>${t('exception')}${icon('arrow')}</button>`;
 if(step===1)body=`<h2>${spg?'Dengarkan kebutuhan, siapkan planogram':'Merchandising terlebih dahulu'}</h2><p class="muted">${spg?'Dengarkan kebutuhan tanpa memaksa. Dokumentasikan planogram sebelum dan sesudah.':'Periksa stok, servis POSM, rapikan planogram. Selesaikan sebelum engage.'}</p><div class="field-grid">${field('SKU / kategori TRW','stock_sku','text',f.stock_sku,'required maxlength="100"')}${field('Jumlah stok','stock_qty','number',f.stock_qty,'min="0" max="100000" required')}</div>${check(t('posm'),'posm',f.posm)}${check(t('planogram'),'planogram',f.planogram)}<div class="camera-grid">${photoInput('before',draft.photos.before)}${photoInput('after',draft.photos.after)}</div>`;
 if(step===2)body=`<h2>${spg?'Jelaskan dengan percaya diri':'Engage retailer & commercial learning'}</h2><div class="note-box">${spg?'Gunakan materi produk yang disetujui brand. Jelaskan manfaat sesuai kebutuhan, beri ruang pelanggan memutuskan.':'Kebutuhan outlet dicatat setelah merchandising selesai. Jangan menjanjikan stok/harga sebelum konfirmasi client.'}</div>${area(spg?'Kebutuhan / pertanyaan pelanggan':'Pertanyaan & kebutuhan retailer','retailer_questions',f.retailer_questions||'','required maxlength="1500"')}${area('Catatan kompetitor (atau tulis tidak ada)','competitor',f.competitor||'','maxlength="1000"')}${select('Tingkat ketertarikan','interest',['none','low','medium','high'],f.interest)}${area(t('nextAction'),'next_action',f.next_action,'required maxlength="500"')}`;
 if(step===3)body=exception?`<h2>${t('exception')}</h2>${select(t('reason'),'exception_reason',reasons,f.exception_reason||'outlet_closed')}${area(t('note'),'exception_note',f.exception_note||'','required maxlength="1000"')}${photoInput('exception',draft.photos.exception)}${area(t('nextAction'),'next_action',f.next_action,'required maxlength="500"')}<div class="notice">Exception masih menunggu bukti dan persetujuan supervisor dengan referensi client.</div>`:`<h2>${spg?'Capture insight & review evidence':'Close · review evidence'}</h2><div class="summary-row"><span>Outlet</span><b>${esc(assignment.outlet.name)}</b></div><div class="summary-row"><span>GPS</span><b>${draft.gps?Math.round(draft.gps.accuracy)+' m':'—'}</b></div><div class="summary-row"><span>Stock / POSM / planogram</span><b>${esc(f.stock_qty)} · ${f.posm?'✓':'—'} · ${f.planogram?'✓':'—'}</b></div><div class="summary-row"><span>Before / after</span><b>${draft.photos.before?'✓':'—'} / ${draft.photos.after?'✓':'—'}</b></div><div class="summary-row"><span>${t('nextAction')}</span><b>${esc(f.next_action)}</b></div>${spg?'<p class="muted" style="margin-top:20px">Setelah visit tersimpan, buka Survey pelanggan pada Hari ini. Target 10 responden valid per workshop-week, sukarela dan consent wajib.</p>':''}<div class="note-box" style="margin-top:20px">${navigator.onLine?'Data masuk antrean lalu sync otomatis.':'Offline: data + foto tersimpan pada perangkat. Sync saat online.'} Accepted baru dihitung setelah review.</div>`;
 root.innerHTML=heading(labels[step],assignment.outlet.name)+`<div class="wizard" data-field-draft="${draft.id}"><div class="card"><div class="stepper">${labels.map((s,i)=>`<div class="step ${step===i?'active':''}"><b>0${i+1}</b>${s}</div>`).join('')}</div><form id="visit-form">${body}</form></div><div class="sticky-actions"><button class="btn secondary" data-back>${icon('arrow','back-arrow')}${step===0?t('cancel'):t('back')}</button><div class="stack"><button class="btn ghost" data-save>Draft</button><button class="btn primary" data-next>${step===3?t('submit'):t('next')}${icon(step===3?'check':'arrow')}</button></div></div></div>`;
 root.querySelector('[data-gps]')?.addEventListener('click',async e=>{const button=e.currentTarget;button.disabled=true;try{await save();draft.gps=await location();await saveDraft(draft);render();}catch(err){toast(err.message,true);button.disabled=false;}});
 root.querySelectorAll('[data-camera]').forEach(el=>el.onchange=async()=>{try{await save();el.disabled=true;const photo=await compressPhoto(el.files[0]);draft.photos[el.dataset.camera]=photo;await saveDraft(draft);render();}catch(err){toast(err.message,true);el.disabled=false;}});
 root.querySelector('[data-exception]')?.addEventListener('click',async()=>{await save();if(!draft.gps)return toast('GPS wajib sebelum mencatat exception.',true);exception=true;step=3;await save();render();});
 root.querySelector('[data-back]').onclick=async()=>{await save();if(step===0){app.navigate('today');return;}if(exception){exception=false;step=0;}else step--;draft.step=step;await saveDraft(draft);render();};
 root.querySelector('[data-save]').onclick=async()=>{await save();toast('Draft tersimpan pada perangkat.');};
 root.querySelector('[data-next]').onclick=async e=>{const button=e.currentTarget;const form=root.querySelector('#visit-form');if(!form.reportValidity())return;button.disabled=true;try{await save();
   if(step===0){if(!draft.gps)throw new Error('Ambil lokasi GPS dahulu.');if(!draft.fields.permission)throw new Error('Izin kerja wajib. Gunakan exception jika tidak diizinkan.');}
   if(step===1&&(!draft.fields.posm||!draft.fields.planogram||!draft.photos.before||!draft.photos.after))throw new Error('Selesaikan POSM, planogram, dan foto sebelum/sesudah.');
   if(step<3){step++;draft.step=step;await saveDraft(draft);render();return;}
   if(app.state.demo)throw new Error('Pratinjau demo hanya-baca. Hubungkan backend untuk menyimpan visit.');
   if(exception&&!draft.photos.exception)throw new Error('Foto exception wajib.');
   if(!exception&&(!draft.gps||!draft.fields.permission||!draft.fields.posm||!draft.fields.planogram||!draft.photos.before||!draft.photos.after))throw new Error('Bukti merchandising belum lengkap.');
   button.disabled=true;const startId=crypto.randomUUID(),submitId=crypto.randomUUID(),items=[{id:startId,action:'visit.start',payload:{visit_id:draft.id,assignment_id:assignment.id,outlet_id:assignment.outlet_id,date:draft.date,started_at:draft.startedAt,gps:draft.gps}}],photoIds=[];
   for(const [kind,photo]of Object.entries(draft.photos)){const id=crypto.randomUUID();photoIds.push(id);items.push({id,action:'photo.upload',dependsOn:[startId],payload:{visit_id:draft.id,photo_id:photo.id,kind,base64:photo.base64,captured_at:photo.capturedAt}});}
   const f=draft.fields,payload=exception?{visit_id:draft.id,exception:{reason:f.exception_reason,note:f.exception_note},next_action:f.next_action}:{visit_id:draft.id,permission:f.permission,posm:f.posm,planogram:f.planogram,stock:[{sku:f.stock_sku,qty:Number(f.stock_qty)}],retailer_questions:f.retailer_questions,competitor:f.competitor,interest:f.interest,next_action:f.next_action};
   items.push({id:submitId,action:'visit.submit',dependsOn:[startId,...photoIds],payload});draft.queued=true;draft.submitRequestId=submitId;draft.photos={};await enqueueBatch(owner,items,draft);toast(t('queued'));scheduleSync();app.navigate('today');
 }catch(err){toast(err.message,true);if(button.isConnected)button.disabled=false;}};
 root.querySelector('form').addEventListener('change',save);};render();}
export async function surveyDialog(app,visits,local=[]){const candidates=[...visits.filter(v=>v.kind==='spg'&&['pending','approved'].includes(v.status)).map(v=>({id:v.id,label:app.state.bootstrap.outlets.find(o=>o.id===v.outlet_id)?.name||v.outlet_id})),...local.filter(d=>d.queued&&d.kind==='spg').map(d=>({id:d.id,label:d.assignment.outlet.name,dependsOn:d.submitRequestId}))];const unique=[...new Map(candidates.map(v=>[v.id,v])).values()];if(!unique.length)return toast('Selesaikan visit SPG sebelum survey.',true);let customers=app.state.bootstrap.customers||[];try{customers=await app.load('customer.list');}catch(e){if(e.code!=='NETWORK')throw e;}dialog('TRW Confidence Conversation · Survey',select('Kunjungan workshop','visit_id',options(unique,'label'),'','required')+surveyFields()+select('Pelanggan loyalty (opsional)','customer_id',options(customers,'label'))+formFooter(t('submit')),async d=>{if(app.state.demo)throw new Error('Demo hanya-baca.');const v=unique.find(v=>v.id===d.visit_id),requestId=crypto.randomUUID();await enqueueBatch(app.state.session.user.id,[{id:requestId,action:'survey.submit',dependsOn:v.dependsOn?[v.dependsOn]:[],payload:{visit_id:d.visit_id,eligible:d.eligible,consent:d.consent,consent_at:new Date().toISOString(),customer_id:d.customer_id||'',answers:{decision_driver:d.decision_driver,brand_preference:d.brand_preference,confidence:Number(d.confidence),need:d.need,respondent_ref:d.respondent_ref}}}]);scheduleSync();toast(t('queued'));});}
