import {t,lang} from './i18n.js';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={today:'M3 10 12 3l9 7v10H3V10m6 10v-7h6v7',reports:'M4 20V10m8 10V4m8 16v-7',leads:'M8 4h12v16H4V8m0 0 4-4v4H4m4 4h8m-8 4h5',loyalty:'M3 8h18v12H3V8m9 0v12m-9-7h18M12 8C3 8 5 1 9 4l3 4m0 0c9 0 7-7 3-4l-3 4',training:'m2 8 10-5 10 5-10 5L2 8m4 3v7l6 3 6-3v-7m4-3v8',review:'M9 3H4v18h16V3h-5M9 2h6v4H9V2m-1 11 3 3 5-6',schedule:'M4 5h16v16H4V5m0 5h16M8 2v6m8-6v6',admin:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 3l3 2 5-3 5 3 3-2 2 7-2 4 1 6-7 2-5-3-5 1-2-7 2-5-2-3',sync:'M3 11a9 9 0 0 1 15-7l3 3m0-5v5h-5m5 6A9 9 0 0 1 6 20l-3-3m0 5v-5h5',arrow:'m8 4 8 8-8 8',check:'m4 12 5 5L20 5',camera:'M3 7h4l2-3h6l2 3h4v14H3V7m9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8',pin:'M12 22s8-9 8-14a8 8 0 1 0-16 0c0 5 8 14 8 14m0-18a4 4 0 1 0 0 8 4 4 0 0 0 0-8',menu:'M3 6h18M3 12h18M3 18h18',plus:'M12 4v16M4 12h16',logout:'M9 3H3v18h6m2-9h10m-5-5 5 5-5 5',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8m0-8v3m0 18v3M0 12h3m18 0h3M3 3l2 2m14 14 2 2M3 21l2-2M19 5l2-2',close:'m5 5 14 14M5 19 19 5',download:'M12 3v12m-5-5 5 5 5-5M3 17v4h18v-4',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m0 4v5l4 3',users:'M8 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M1 21v-4a7 7 0 0 1 14 0v4m1-18a4 4 0 0 1 0 8m3 3a6 6 0 0 1 4 7',shield:'m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6l9-4m-4 10 3 3 5-6'};
export const icon=(name,cls='')=>`<svg class="icon ${esc(cls)}" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.today}"/></svg>`;
export const money=v=>new Intl.NumberFormat(lang()==='id'?'id-ID':'en-US',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0);
export const number=v=>new Intl.NumberFormat(lang()==='id'?'id-ID':'en-US').format(v||0);
export function dateLabel(value){return new Intl.DateTimeFormat(lang()==='id'?'id-ID':'en-GB',{dateStyle:'full',timeZone:'Asia/Jakarta'}).format(new Date(value+'T12:00:00+07:00'));}
export function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export function toast(message,error=false){const el=document.querySelector('#toast');el.textContent=message;el.className=error?'visible error':'visible';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.className='',5000);}
export const badge=(text,kind='neutral')=>`<span class="badge ${esc(kind)}">${esc(text)}</span>`;
export function statusBadge(value){const names={pending:t('pending'),approved:t('completed'),draft:'Draft',planned:t('planned'),issued:'Issued',valid:t('pass'),blocked:'Perlu diperbaiki','client-approved exception':'Client exception'};return badge(names[value]||value,['approved','valid','redeemed','completed','delivered'].includes(value)?'good':['rejected','blocked','failed','expired','void'].includes(value)?'bad':['pending','queued','manual_pending','validated','retry'].includes(value)?'warn':'neutral');}
export const empty=(text=t('empty'))=>`<div class="empty">${icon('leads')}<p>${esc(text)}</p></div>`;
export function field(label,name,type='text',value='',extra=''){const id='f-'+name;return `<label class="field" for="${esc(id)}"><span>${esc(label)}</span><input id="${esc(id)}" name="${esc(name)}" type="${esc(type)}" value="${esc(value)}" ${extra}></label>`;}
export function area(label,name,value='',extra=''){return `<label class="field" for="f-${esc(name)}"><span>${esc(label)}</span><textarea id="f-${esc(name)}" name="${esc(name)}" rows="3" ${extra}>${esc(value)}</textarea></label>`;}
export function select(label,name,options,value='',extra=''){return `<label class="field" for="f-${esc(name)}"><span>${esc(label)}</span><select id="f-${esc(name)}" name="${esc(name)}" ${extra}>${options.map(o=>{const v=typeof o==='string'?o:o.value,label=typeof o==='string'?o:o.label;return `<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(label)}</option>`;}).join('')}</select></label>`;}
export function check(label,name,checked=false,extra=''){return `<label class="checkbox"><input type="checkbox" name="${esc(name)}" ${checked?'checked':''} ${extra}><span>${esc(label)}</span></label>`;}
export function options(rows,label='name'){return [{value:'',label:'— '+t('all')+' —'},...rows.map(r=>({value:r.id,label:r[label]||r.id}))];}
export function values(form){const data=Object.fromEntries(new FormData(form));for(const el of form.querySelectorAll('input[type=checkbox]'))data[el.name]=el.checked;return data;}
export function formFooter(label=t('save')){return `<div class="dialog-actions"><button type="button" class="btn secondary" data-close>${t('cancel')}</button><button type="submit" class="btn primary">${esc(label)}</button></div>`;}
export function dialog(title,body,submit){document.querySelector('dialog')?.remove();const el=document.createElement('dialog');el.className='modal';el.innerHTML=`<form method="dialog" id="dialog-form"><div class="dialog-title"><h2>${esc(title)}</h2><button type="button" class="btn icon-only secondary" data-close aria-label="${t('close')}">${icon('close')}</button></div>${body}</form>`;document.body.append(el);el.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>el.close());el.addEventListener('close',()=>el.remove());el.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=el.querySelector('button[type=submit]');if(btn)btn.disabled=true;try{await submit?.(values(e.target),e.target,el);if(el.open)el.close();}catch(err){toast(err.message,true);}finally{if(btn)btn.disabled=false;}};el.showModal();return el;}
export function download(data){const blob=new Blob([data.content],{type:data.mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=data.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function table(columns,rows,{selectable=false,key='id',name='data'}={}){return `<div class="table-toolbar"><label class="search">${icon('leads')}<span class="sr-only">${t('search')}</span><input data-filter="${esc(name)}" type="search" placeholder="${t('search')}…"></label><span class="muted">${number(rows.length)} records</span></div><div class="table-scroll"><table data-table="${esc(name)}"><thead><tr>${selectable?'<th scope="col"><span class="sr-only">Select</span></th>':''}${columns.map((c,i)=>`<th scope="col"><button class="sort" type="button" data-sort="${i+(selectable?1:0)}">${esc(c.label)} <span aria-hidden="true">↕</span></button></th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr data-key="${esc(r[key])}">${selectable?`<td><input type="checkbox" name="selected" value="${esc(r[key])}" aria-label="Select ${esc(r[key])}"></td>`:''}${columns.map(c=>`<td>${c.render?c.render(r):esc(r[c.key])}</td>`).join('')}</tr>`).join('')}</tbody></table>${rows.length?'':empty()}</div>`;}
export function bindTables(root=document){root.querySelectorAll('[data-filter]').forEach(el=>{el.oninput=()=>{const table=root.querySelector(`[data-table="${el.dataset.filter}"]`);table?.querySelectorAll('tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(el.value.toLowerCase()));};});root.querySelectorAll('[data-sort]').forEach(b=>{b.onclick=()=>{const body=b.closest('table').querySelector('tbody'),col=Number(b.dataset.sort),direction=b.dataset.direction==='asc'?-1:1;b.dataset.direction=direction===1?'asc':'desc';const rows=[...body.children];rows.sort((a,c)=>a.children[col].textContent.localeCompare(c.children[col].textContent,undefined,{numeric:true})*direction);rows.forEach(row=>body.append(row));};});}
